migrate NuGet.Services.DatabaseMigration.Facts to sdk csproj
NuGet/NuGetGallery pull request #10001
Opened 2024-06-05 06:10 UTC by SimonCropp

2024-06-05 13:42 UTC, joelverhagen commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\NuGet.Services.Entities\NuGet.Services.Entities.csproj" />
I think some of these Project references are not needed because SDK csproj handles transitive project references better (historically, legacy csproj may have improved without my knowledge).

2024-06-06 06:05 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\NuGet.Services.Entities\NuGet.Services.Entities.csproj" />
NuGet.Services.Entities still required but NuGetGallery.Core isnt

2024-06-06 10:32 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\NuGet.Services.Entities\NuGet.Services.Entities.csproj" />
actually. u r correct. i was able to remove a few more

2024-06-22 00:01 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" PrivateAssets="all" />
Should we keep `<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>`?

2024-06-22 00:02 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> -    <ProjectReference Include="..\..\src\NuGet.Services.Entities\NuGet.Services.Entities.csproj">
Why was this one removed? Was it unnecessary?

2024-06-22 00:02 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> -      <Project>{097b2cdd-9623-4c34-93c2-d373d51f5b4e}</Project>
Same here.

2024-06-22 00:03 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\DatabaseMigrationTools\DatabaseMigrationTools.csproj" />
Doesn't project references go before package reference by default?

2024-06-22 00:57 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\DatabaseMigrationTools\DatabaseMigrationTools.csproj" />
there is no default. but i have changed it

2024-06-22 00:57 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> -      <Project>{097b2cdd-9623-4c34-93c2-d373d51f5b4e}</Project>
i think it gets that ref transitively

2024-06-22 00:57 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> -    <ProjectReference Include="..\..\src\NuGet.Services.Entities\NuGet.Services.Entities.csproj">
i think it gets that ref transitively

2024-06-22 00:58 UTC, SimonCropp commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" PrivateAssets="all" />
functionally equivalent in this context. and less code

2024-06-22 01:28 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" PrivateAssets="all" />
Not really the same, now it's defaulting to `all` which is equivalent to include `compile, buildTransitive .. ` etc assets, since it's test project most likely not really matter, but just in case I want it to be same as before.  https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

2024-06-27 03:35 UTC, erdembayar approved these changes
👏 
Thank you for your contributions.

2024-06-27 03:37 UTC, erdembayar commented on tests/NuGet.Services.DatabaseMigration.Facts/NuGet.Services.DatabaseMigration.Facts.csproj
> +    <ProjectReference Include="..\..\src\DatabaseMigrationTools\DatabaseMigrationTools.csproj" />
Just realized `ProjectReference` and `PackageReferences` needs to be separated. 

```
<ItemGroup>
  <ProjectReference Include="..\..\src\DatabaseMigrationTools\DatabaseMigrationTools.csproj" />
</ItemGroup>
<ItemGroup>
 <PackageReference Include="Moq" Version="4.8.2" />
</ItemGroup>

```

2024-06-27 03:38 UTC, erdembayar requested changes
Sorry, minor change request, please separate references in separate `ItemGroups`

2024-07-09 17:19 UTC, erdembayar approved these changes

2024-07-09 18:36 UTC, merged