move to Microsoft.WindowsAzure.SDK
NuGet/NuGetGallery pull request #10031
Opened 2024-06-22 00:26 UTC by SimonCropp

so contributors can build without the legacy azure sdk installed

2024-06-24 04:19 UTC, erdembayar requested changes
Identity of package author is unknown even though it says Microsoft in the prefix, most likely it predates our [prefix reservation](https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation). https://www.nuget.org/packages/Microsoft.WindowsAzure.SDK#readme-body-tab

Due to supply chain security concern I believe shouldn't accept this change, it's . It looks like `Microsoft.ApplicationInsights` is new replacement for this.

2024-06-24 05:07 UTC, SimonCropp commented
so will you be doing the Microsoft.ApplicationInsights change?

2024-06-24 13:30 UTC, joelverhagen commented
It would be worth identifying whether these dependencies are even needed any more. IIRC part of the reason we had them is because we were running on Azure Cloud Service which is a long ago deprecated service. We now run on Azure App Service so perhaps this and the dependent code is actually dead.

2024-06-24 16:04 UTC, erdembayar commented
> so will you be doing the Microsoft.ApplicationInsights change?

Currently, we don't have bandwidth for this right now. Maybe in the future yes. Unless it's blocking the build I would create the tracking issue and close the PR for now.

2024-06-25 01:46 UTC, SimonCropp commented
well it is a fairly significant blocker to anyone wanting to contribute

2024-06-25 22:55 UTC, erdembayar commented
We have workloads necessary for our repo [here](https://github.com/NuGet/NuGetGallery/blob/main/README.md). So it's not really blocker.

> well it is a fairly significant blocker to anyone wanting to contribute

Could you be able to take stab on this please?

2024-06-26 00:06 UTC, SimonCropp commented
> We have workloads necessary for our repo [here](https://github.com/NuGet/NuGetGallery/blob/main/README.md). So it's not really blocker.

given many people use Rider and VScode. that guidance is not great

2024-07-10 01:23 UTC, closed without merging