remove CacheFilterAttribute
NuGet/NuGetGallery pull request #10034
Opened 2024-06-22 00:47 UTC by SimonCropp

it is not used

2024-06-22 01:39 UTC, erdembayar commented on src/NuGetGallery/Filters/CacheFilter.cs
> -    public sealed class CacheFilterAttribute : ActionFilterAttribute
@NuGet/gallery-team 
Is it something we consume somewhere in our internal project via packaging or MEF?

2024-06-22 01:46 UTC, SimonCropp commented on src/NuGetGallery/Filters/CacheFilter.cs
> -    public sealed class CacheFilterAttribute : ActionFilterAttribute
i doubt it, give NuGetGallery does not produce a nuget

2024-06-25 23:01 UTC, erdembayar approved these changes

2024-06-27 23:21 UTC, SimonCropp commented
can this be merged?

2024-07-09 18:39 UTC, erdembayar commented
@SimonCropp 
CI build fails. It fails missing dependency to `Gallery.GalleryTools.nuspec`

2024-07-09 18:42 UTC, erdembayar requested changes
Code doesn't compile anymore.

2024-07-10 01:20 UTC, SimonCropp commented
fixed

2024-07-10 01:23 UTC, closed without merging