Add package version to query string for v2 CDN endpoint (#10082)
NuGet/NuGetGallery pull request #10083
Opened 2024-07-26 20:59 UTC by clairernovotny

#### PR Classification
New feature: Added support for handling a version parameter in cloud blob storage services#.

#### PR Summary
Introduced a version parameter to enhance file storage service methods and updated related tests.
- `CloudBlobFileStorageService.cs`: Modified constructor and methods to handle `versionParameter`.
- `IFileStorageService`: Updated interface to include `versionParameter`.
- `FileSystemFileStorageService.cs`: Updated methods to handle `versionParameter`.
- `PackageFileService`: Passed `versionParameter` in method calls.
- Updated tests in `CloudBlobFileStorageServiceFacts`, `FileSystemFileStorageServiceFacts`, and `PackageFileServiceFacts` to include `versionParameter`.

2024-07-29 12:40 UTC, joelverhagen commented on src/NuGetGallery.Services/Storage/CloudBlobFileStorageService.cs
> +        public async Task<ActionResult> CreateDownloadFileActionResultAsync(Uri requestUrl, string folderName, string fileName, string versionParameter)
This is a low level method not specific to a package or version. What do you think about a simple `queryString` parameter instead?

2024-07-29 12:42 UTC, joelverhagen commented on src/NuGetGallery/Services/PackageFileService.cs
> +            var packageVersion = NuGetVersionFormatter.GetNormalizedPackageVersion(package).ToLowerInvariant(); // will not return null bc BuildFileName will throw if values are null
Why lower invariant? Generally we use the original casing when we have it and allow the user of the value to do the comparison in a case insensitive manner if necessary. This means we can retain that original author intent as much as possible.

2024-07-29 12:52 UTC, joelverhagen commented on src/NuGetGallery/Services/PackageFileService.cs
>          public Task<ActionResult> CreateDownloadPackageActionResultAsync(Uri requestUrl, Package package)
Might a good time to refactor this method to call the other overload below

2024-07-29 12:53 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
We generally leave System* at the top, then the rest alphabetical, without spacing. IDE manages this as you add types so much organization is not very useful at scale.

2024-07-29 13:14 UTC, joelverhagen commented on src/NuGetGallery/Services/SymbolPackageFileService.cs
> +            var packageVersion = NuGetVersionFormatter.GetNormalizedPackageVersion(symbolPackage.Package).ToLowerInvariant(); // will not return null bc BuildFileName will throw if values are null
Same comments as above

2024-07-29 13:14 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
No need to organize usings. IDE will mess it up as we go.

2024-07-29 13:14 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
Unless it's possible to add it to encode the rule editorconfig

2024-07-29 13:15 UTC, joelverhagen requested changes
Minor comments

2024-07-29 17:45 UTC, jimmylewis commented on tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
Moreover, this is an unsorted order that will cause the IDE to not know where to put new usings, and then it will always append.  By keeping it sorted (System first even), the IDE will be able to maintain the order.

2024-07-29 18:09 UTC, jimmylewis requested changes

2024-07-29 18:09 UTC, jimmylewis commented on src/NuGetGallery/Services/PackageFileService.cs
> +            var packageVersion = NuGetVersionFormatter.GetNormalizedPackageVersion(package).ToLowerInvariant(); // will not return null bc BuildFileName will throw if values are null
nit: please don't use abbreviations that not all people will recognize (e.g. `bc` => `because`)

2024-07-29 18:25 UTC, erdembayar commented on src/NuGetGallery.Services/Storage/CloudBlobFileStorageService.cs
> +            var nvcol = HttpUtility.ParseQueryString(query);
Explicit type please

2024-07-29 18:28 UTC, erdembayar commented
Please add tracking issue link in description.

2024-07-29 18:35 UTC, clairernovotny commented on src/NuGetGallery.Services/Storage/CloudBlobFileStorageService.cs
> +        public async Task<ActionResult> CreateDownloadFileActionResultAsync(Uri requestUrl, string folderName, string fileName, string versionParameter)
I looked a bit closer and the easiest approach hardcodes the parameter name lower down--this just passes the version. Making it more generic would also put the burden on a properly urlencoded query string on the caller.

2024-07-29 18:43 UTC, clairernovotny commented on src/NuGetGallery/Services/PackageFileService.cs
>          public Task<ActionResult> CreateDownloadPackageActionResultAsync(Uri requestUrl, Package package)
I looked at this, however that would create more duplication of parameter validation logic that's lower down.

2024-07-29 19:04 UTC, clairernovotny commented on tests/NuGetGallery.Facts/Services/CloudBlobFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
Fixed by adding an editorconfig that specifies the sort. Was done by formatting on save automaticaly.

2024-07-29 19:33 UTC, clairernovotny commented on tests/NuGetGallery.Facts/Services/FileSystemFileStorageServiceFacts.cs
> +using NuGetGallery.Configuration;
I've added an editorconfig to the repo to resolve this.

2024-07-29 20:15 UTC, jimmylewis commented on .editorconfig
> +csharp_indent_labels = no_change
nit: ironically this file doesn't have a trailing newline. 😜

2024-07-29 20:15 UTC, jimmylewis commented on .editorconfig
> +dotnet_diagnostic.IDE0005.severity = error
nit: would be nice to keep the diagnostics alphabetically sorted by ID, as we will likely add more rules over time, and duplicates are tedious to find when the list is long.

2024-07-31 19:06 UTC, jimmylewis approved these changes
LGTM with a few nits, but I'll defer to Joel for his design feedback comments.

2024-07-31 19:06 UTC, jimmylewis commented on src/NuGetGallery/Services/FileSystemFileStorageService.cs
> +using NuGetGallery.Configuration;
nit: this file and a few others modified in this PR don't adhere to the new style rules put in place by this PR (.editorconfig).

2024-08-01 14:07 UTC, joelverhagen submitted a review, later dismissed

2024-08-01 14:07 UTC, joelverhagen commented on src/NuGetGallery/Services/PackageFileService.cs
>          public Task<ActionResult> CreateDownloadPackageActionResultAsync(Uri requestUrl, Package package)
Sounds good. It's not a big deal one way or the other.

2024-08-01 14:08 UTC, joelverhagen commented on src/NuGetGallery.Services/Storage/CloudBlobFileStorageService.cs
> +        public async Task<ActionResult> CreateDownloadFileActionResultAsync(Uri requestUrl, string folderName, string fileName, string versionParameter)
Seems okay to me. A `Dictionary<string, string>` would be more flexible. but it's not a big deal to me.

2024-08-01 15:48 UTC, joelverhagen commented on .editorconfig
> +dotnet_diagnostic.CA2017.severity = suggestion
Did you switch all of them? Or just ones that are failing right now? It might be best to be as strict as possible right now, without introducing more errors given the codebase in its current state

2024-08-01 15:49 UTC, joelverhagen commented on .editorconfig
> +dotnet_diagnostic.CA2017.severity = suggestion
I don't feel strongly.

2024-08-01 16:05 UTC, clairernovotny commented on .editorconfig
> +dotnet_diagnostic.CA2017.severity = suggestion
switched all of them for now until we can be more intentional

2024-08-01 16:05 UTC, joelverhagen approved these changes

2024-08-01 16:10 UTC, merged