Add a Python module for log version parsing
NuGet/NuGetGallery pull request #10107
Opened 2024-08-02 18:20 UTC by clairernovotny

A building block for https://github.com/NuGet/Engineering/issues/5082

2024-08-02 18:24 UTC, joelverhagen commented on NuGet.Jobs.sln
> +Project("{888888A0-9F3D-457C-B088-3A5042F75D52}") = "StatsLogParser", "src\StatsLogParser\StatsLogParser.pyproj", "{6DEFB0FC-4057-4F1B-81B4-6DF4F75A1233}"
Will editing of this happen in VS or VS Code?

2024-08-02 20:25 UTC, clairernovotny commented on NuGet.Jobs.sln
> +Project("{888888A0-9F3D-457C-B088-3A5042F75D52}") = "StatsLogParser", "src\StatsLogParser\StatsLogParser.pyproj", "{6DEFB0FC-4057-4F1B-81B4-6DF4F75A1233}"
Either. There's a pyproj that was added to VS. Any reason not to support both?

2024-08-02 20:43 UTC, erdembayar commented on src/StatsLogParser/.vscode/settings.json
> +        "-v",
Nit: It looks there's extra tab space here

2024-08-02 21:19 UTC, erdembayar commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
Does it can handle edge cases? For example `2.1.0-beta1-build2945` is valid version according to NuGet.Version parser, but if I pass same input to this code snippet then it return `false`.
<img width="443" alt="image" src="https://github.com/user-attachments/assets/0157950b-de59-4470-89c2-af955396df03">
<img width="521" alt="image" src="https://github.com/user-attachments/assets/cb4db8d2-de81-4123-85fe-a60c35a5a2f1">

2024-08-02 21:21 UTC, erdembayar commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
It was able to handle `2.1.0-beta1`
<img width="487" alt="image" src="https://github.com/user-attachments/assets/b90c9f58-ccbf-45c8-98c0-bddde8e5435c">

2024-08-02 21:22 UTC, erdembayar commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
I used below code testing
```

from __future__ import annotations
from dataclasses import dataclass
from packaging.version import Version, InvalidVersion
import urllib.parse

import re
import sys

class VersionTest:
    @staticmethod
    def is_valid_version(version_string):
        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
        try:
            # Check if it's a valid three-part or four-part version with optional pre-release tag
            Version(version_string)
            return True
        except InvalidVersion:
            # Check if it's a valid four-part version with optional pre-release tag
            parts = version_string.split('.')
            if len(parts) == 4:
                main_version = '.'.join(parts[:3])
                pre_release = parts[3]
                try:
                    Version(main_version)
                    if pre_release.isdigit() or '-' in pre_release:
                        return True
                except InvalidVersion:
                    pass
        return False

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python versionTest.py <version_string>")
        sys.exit(1)
    
    version_string = sys.argv[1]
    is_valid = VersionTest.is_valid_version(version_string)
    
    if is_valid:
        print(f"The version '{version_string}' is valid.")
    else:
        print(f"The version '{version_string}' is invalid.")

```

2024-08-02 21:32 UTC, jimmylewis commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
does it also need to account for semver metadata such as `1.2.3.4+metadata`?

2024-08-02 21:35 UTC, erdembayar commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
Yes, it can handle `1.2.3.4+metadata`
<img width="503" alt="image" src="https://github.com/user-attachments/assets/98ca1c37-3d9c-4bf5-bcff-834058ebbd43">

2024-08-05 17:33 UTC, joelverhagen commented on NuGet.Jobs.sln
> +Project("{888888A0-9F3D-457C-B088-3A5042F75D52}") = "StatsLogParser", "src\StatsLogParser\StatsLogParser.pyproj", "{6DEFB0FC-4057-4F1B-81B4-6DF4F75A1233}"
Unless we want to direct folks to always have pyproj support installed (additional workload?) it might be better to keep it out of the core editing experience. I think we may need all of our CI agents to have support too.

2024-08-06 14:45 UTC, joelverhagen commented on src/StatsLogParser/loginterpretation/nugetversion.py
> +    def parse_version(version_string: str) -> Tuple[int, int, int, int]:
nit: `namedtuple` for major, minor, build, revision instead of `tuple`

2024-08-06 14:50 UTC, joelverhagen commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("5.0.0.0", "5.0.0", "http://localhost/packages/5.0.0.0.5.0.0.nupkg"),
perhaps try all of the possible {id}.{version} combinations? splitting them to a negative test case if needed (error thrown, null returned or whatever is the desired behavior)
http://localhost/packages/1.nupkg
http://localhost/packages/1.2.nupkg
http://localhost/packages/1.2.3.nupkg
...
http://localhost/packages/1.2.3.4.5.6.7.8.9.nupkg

2024-08-06 14:53 UTC, joelverhagen commented
We should have a step (perhaps opt in) to `build.ps1` or the CI YAML to run the pytests. If they are not run automatically, they have pretty limited value IMO.

2024-08-06 14:53 UTC, joelverhagen commented
I think this is a good size, roughly for the first PR. If much more functionality is needed it might be better as a 2nd PR.

2024-08-06 14:53 UTC, joelverhagen requested changes
Minor comments, need a plan for running the tests automatically somewhere, sometime

2024-08-06 17:27 UTC, clairernovotny commented
![image](https://github.com/user-attachments/assets/a4e14f04-fc48-40d5-ad47-e2488f6dc5af)

2024-08-06 17:30 UTC, clairernovotny commented on src/StatsLogParser/loginterpretation/packagedefinition.py
> +        """Check if it's a valid version that support 3 or 4 part versioning with optional pre-release tag"""
This outdated. the current code is using a port of the relevant parts of semanticversion and nugetversion classes.

2024-08-06 17:34 UTC, clairernovotny commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("5.0.0.0", "5.0.0", "http://localhost/packages/5.0.0.0.5.0.0.nupkg"),
would our code create a 1.2.nupkg when uploaded or would it be normalized to 1.2.0.0.nupkg? Would 1.nupkg exist as that'd be missing a version entirely.

2024-08-06 17:34 UTC, clairernovotny commented
> We should have a step (perhaps opt in) to `build.ps1` or the CI YAML to run the pytests. If they are not run automatically, they have pretty limited value IMO.

Agreed, though for timing, we'll come back to that later.

2024-08-06 17:37 UTC, joelverhagen submitted a review, later dismissed
Minor comments. LGTM.

2024-08-06 17:58 UTC, clairernovotny commented on .gitignore
> +!.vscode/*.code-snippets
I think this should be in all of our gitignores

2024-08-06 18:28 UTC, erdembayar commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("xunit.1", "2.4.1-beta.1.build3958", "http://localhost/packages/xunit.1.2.4.1-beta.1.build3958.nupkg?packageVersion=2.4.1-beta.1.build3958"),
Can you include `2.1.0-beta1-build2945` test? It has `-` 2 times.

2024-08-06 18:39 UTC, joelverhagen commented on .gitignore
> +!.vscode/*.code-snippets
Yes, but it could be below the `# Repository specific #` line to clearly show what came from `https://github.com/github/gitignore/blob/main/VisualStudio.gitignore` and what was added by us

2024-08-06 18:40 UTC, joelverhagen commented on .gitignore
> +##### Python ignores from https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
could this be put in src/StatsLogParser?

2024-08-06 18:41 UTC, joelverhagen commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("5.0.0.0", "5.0.0", "http://localhost/packages/5.0.0.0.5.0.0.nupkg"),
This would be a negative test (assert error or null response). Our code would not produce that. The shortest would be `1.2.3.4`, being ID 1 version 2.3.4.

2024-08-06 20:07 UTC, clairernovotny commented on .gitignore
> +##### Python ignores from https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
I supposed it could, though that would seem to make more work later? Any reason not to keep it at the root?

2024-08-06 20:11 UTC, clairernovotny commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("xunit.1", "2.4.1-beta.1.build3958", "http://localhost/packages/xunit.1.2.4.1-beta.1.build3958.nupkg?packageVersion=2.4.1-beta.1.build3958"),
Done, with tests passing 
![image](https://github.com/user-attachments/assets/5952cee7-3126-4bc9-9c91-3702242b6a7d)

2024-08-06 20:23 UTC, clairernovotny commented on src/StatsLogParser/tests/test_packagedefinition.py
> +    ("5.0.0.0", "5.0.0", "http://localhost/packages/5.0.0.0.5.0.0.nupkg"),
Done, including a couple tests that highlight the ambiguity

2024-08-06 20:28 UTC, joelverhagen commented on .gitignore
> +##### Python ignores from https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore
Because Python ignores may ignore useful files we would other want to keep in a .NET repo.

2024-08-06 21:05 UTC, joelverhagen approved these changes

2024-08-06 22:05 UTC, merged

2024-08-06 22:53 UTC, agr approved these changes