[Repair Item] Fix unicode character on nuspec.
NuGet/NuGetGallery pull request #10157
Opened 2024-08-24 00:38 UTC by dannyjdev

# Changes
* Adds a new validation to verify `nuspec` file is normalized
* This validation is the same that is done on `db2catalog` job that was not performed on Gallery.

Addresses: https://github.com/NuGet/Engineering/issues/5470

2024-08-26 21:20 UTC, erdembayar commented
Please add tracking issue.

2024-08-26 21:21 UTC, ryuyu commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +            if (result != null)
nit: Wouldn't it be clearer here to directly check for Invalid as opposed to assuming that null means the check didn't fail?

2024-08-26 21:21 UTC, erdembayar commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
Do you have example of invalid entry?

2024-08-26 21:24 UTC, ryuyu commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                return PackageValidationResult.Invalid(Strings.UploadPackage_NuspecContainsInvalidUnicodeCharacters);
nit: it looks like this message is returned if the above stuff fails for any reason. Is unicode characters existing in nuspec the only time this happens? If not, user might be some pretty confusing messaging.

2024-08-26 21:34 UTC, dannyjdev commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +            if (result != null)
I know is a weird way to check if the validation actually passed, here on the [ValidateMetadataBeforeUploadAsync](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Services/PackageMetadataValidationService.cs#L95) there are multiple validations performed and all of them uses the same pattern to check null, I'm just following the that.

2024-08-26 21:49 UTC, jimmylewis requested changes
See comments.  Very suspicious that the return value of IsNormalized() is discarded.

2024-08-26 21:49 UTC, jimmylewis commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
Why doesn't this use the result of calling IsNormalized()?  What if it returns false?

2024-08-26 21:49 UTC, jimmylewis commented on .gitignore
> +!**/TestData/*.nupkg
Can we avoid checking in binary files to git?

2024-08-26 21:49 UTC, jimmylewis commented on tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
> +                var package = TestDataResourceUtility.GetResourceBytes("PackageWithInvalidUnicodeCharacters.1.0.0.nupkg");
Binary test asset files are very opaque to review.  Is there a way this could be refactored so that we can more easily see how the Valid/Invalid inputs are created?  

I'm suspicious on this due to my above comment where IsNormalized() could return false, and AFAICT the code would report is as valid:
* What is testing the IsNormalized() == false code path that doesn't throw?
* What is causing this to be reported as Invalid, such that the test passes?

2024-08-26 21:50 UTC, dannyjdev commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                return PackageValidationResult.Invalid(Strings.UploadPackage_NuspecContainsInvalidUnicodeCharacters);
This happens when the nuspec file (the "unicode string") cannot be normalized using the `NormalizationForm.FormC` type ([NormalizationForm](https://learn.microsoft.com/en-us/dotnet/api/system.text.normalizationform?view=net-8.0#fields)). So yes, that validation fails due to unicode characters that the FormC doesn't accept as valid.

2024-08-26 22:26 UTC, dannyjdev commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
I'm using this method since if the string contains invalid unicodes this will throw an exception that is catched to return this package as Invalid (there is another one that is `Normalize()` that returns the normalized string but it's the same situation), for correctness I think I can use the value and if `IsNormalized()` is false I can add a warning to the validation mentioning that the package nuspec is not normalized, but in the end, I would not like to make a package invalid just cause it is not normalized, I don't know how many packages can fail this test.

2024-08-26 22:53 UTC, jimmylewis commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
In that case, can the method be renamed?  CheckNuspecNormalized seems to indicate the wrong thing if you're just verifying that it's a valid Unicode string.

2024-08-26 22:55 UTC, jimmylewis commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
It also strikes me that by the time you have it stored in `string nuspec`, it's already been deserialized and converted to UTF-16.  Is there a case where calling IsNormalized would throw at this point, or is this last line unnecessary?

2024-08-27 03:27 UTC, dannyjdev commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
Updated, I left it as CheckNuspecNormalized since now I added a warning to verify normalization. Regarding the `string nuspec`, yes, the XML has been converted into a string, but when calling the `IsNormalized()` method it checks that the actual char sequence is normalized and a valid.

This is an example on where it can throw due to invalid character.
``` csharp
string invalidUnicodeChar = "\uD83D";
invalidUnicodeChar.IsNormalized(); // This throws an exception with the message: invalid Unicode code points
```

This is an example on where it can fail normalization
``` csharp
string nonNormalizedString = "e\u0301"; // This is the letter é
Console.WriteLine(nonNormalizedString.IsNormalized()); // False
```

2024-08-27 03:49 UTC, dannyjdev commented on .gitignore
> +!**/TestData/*.nupkg
We have some test cases for corrupted `nupkg` files, these are mostly changed manually by changing bytes. I don't know the case of all of them, but at least for the package that I uploaded I manually changed a byte to contain an invalid unicode that I wasn't able to reproduce in our tests. On our tests we first create the `nuspec` on a string that gets converted into a `Stream` and the stream seems to encode it to a valid version, non normalized char seems to remain the same when the stream gets converted into the package reader but non valid unicode chars seems to be encoded to valid UTF chars.

2024-08-27 03:50 UTC, dannyjdev commented on tests/NuGetGallery.Facts/Services/PackageMetadataValidationServiceFacts.cs
> +                var package = TestDataResourceUtility.GetResourceBytes("PackageWithInvalidUnicodeCharacters.1.0.0.nupkg");
Check these answers for the previous comments:
* https://github.com/NuGet/NuGetGallery/pull/10157#discussion_r1732069803
* https://github.com/NuGet/NuGetGallery/pull/10157#discussion_r1731861459

2024-08-27 18:38 UTC, jimmylewis approved these changes

2024-08-27 21:13 UTC, dannyjdev commented on src/NuGetGallery/Services/PackageMetadataValidationService.cs
> +                nuspec.IsNormalized(NormalizationForm.FormC);
I put an example of an invalid unicode character here: https://github.com/NuGet/NuGetGallery/pull/10157#discussion_r1732069803. As I mentioned on this comment https://github.com/NuGet/NuGetGallery/pull/10157#discussion_r1732084577, I couldn't reproduce a nuspec with that character in our tests so I added a `nupkg` file that I manually corrupted to include it on our unit tests.

2024-08-27 23:03 UTC, merged