Set `SendCertificateChain` option in KeyVaultReader to enable SN+I authentication
NuGet/NuGetGallery pull request #10179
Opened 2024-09-10 22:37 UTC by adityapatwardhan

Summary of the changes (in less than 80 characters):

* Set the ClientCertificateCredentialOptions with SendCertificateChain when the KeyVaultConfiguration is configured with SendCertificateChain

2024-09-10 22:44 UTC, erdembayar commented on src/NuGet.Services.KeyVault/KeyVaultReader.cs
> +                if (_configuration.SendX5c)
@adityapatwardhan 
Do you have a use case for this scenario? Otherwise, we're moving to Managed identity. KV reader is less of a priority for us.

2024-09-10 22:56 UTC, adityapatwardhan commented on src/NuGet.Services.KeyVault/KeyVaultReader.cs
> +                if (_configuration.SendX5c)
PowerShell Gallery is planning to use SN+I. We cannot use Managed Identity for now.

2024-09-10 22:59 UTC, erdembayar commented on src/NuGet.Services.KeyVault/KeyVaultReader.cs
> +                if (_configuration.SendX5c)
I see. Could you be able to add unit tests covering the new code path?

2024-09-10 22:59 UTC, joelverhagen approved these changes

2024-09-10 23:00 UTC, joelverhagen commented
Good point on UT coverage from @erdembayar. This is especially important to assert this behavior is needed by PowerShell Gallery.

2024-09-10 23:00 UTC, joelverhagen requested changes
UTs, so we can protect regressing this code path your team needs.

2024-09-12 12:58 UTC, joelverhagen submitted a review, later dismissed

2024-09-12 23:50 UTC, joelverhagen approved these changes

2024-09-12 23:51 UTC, merged