Dg add vulnerabilities to viewmodels
NuGet/NuGetGallery pull request #8435
Opened 2021-03-01 11:20 UTC by drewgillies

Addresses view model portion of https://github.com/NuGet/NuGetGallery/issues/8361.

The intent is to add an `IsVulnerable` field to the packages listed in the Manage Packages view. The packages listed (in both the listed and unlisted lists) are the latest versions of those packages. If those latest versions are vulnerable, we want to display a warning, indicating that something needs to be done. It will be generic and will direct customers to the Package Details page for more information.

2021-03-02 18:21 UTC, joelverhagen commented on src/NuGetGallery.Services/PackageManagement/PackageService.cs
> +                result = result.Include($"{nameof(Package.VulnerablePackageRanges)}.{nameof(VulnerablePackageVersionRange.Vulnerability)}");
Ideally this is done with the `Expression<Func<...>>` include style used above. Can that be done or is there some blocker?

2021-03-02 18:22 UTC, joelverhagen commented on src/NuGetGallery/Services/IPackageVulnerabilitiesService.cs
> +        bool PackageIsVulnerable(Package package);
nit `IsPackageVulnerable`

2021-03-02 18:23 UTC, joelverhagen commented on src/NuGetGallery/Services/PackageVulnerabilitiesService.cs
> +            package != null
I think it'd be fine to throw `ArgumentNullException` if someone provides a null package. The caller should be more careful than that. I think it is nonsensical to say that a null package is not vulnerable.

2021-03-02 18:24 UTC, joelverhagen commented
Does this PR have performance issues? I vaguely remember you mentioning that this additional include tanks the performance for owners with many, many packages. Perhaps I am misremembering.

2021-03-02 18:25 UTC, joelverhagen requested changes
Questions/comments.

2021-03-08 05:48 UTC, drewgillies commented on src/NuGetGallery.Services/PackageManagement/PackageService.cs
> +                result = result.Include($"{nameof(Package.VulnerablePackageRanges)}.{nameof(VulnerablePackageVersionRange.Vulnerability)}");
The blocker is the nesting. A second level of nesting could be addressed in .NET Core with a `ThenInclude` but the way to do it here is via a string.

2021-03-08 05:54 UTC, drewgillies commented
> Does this PR have performance issues? I vaguely remember you mentioning that this additional include tanks the performance for owners with many, many packages. Perhaps I am misremembering.

No, that was the earlier implementation where I queried the entire set of a package's versions to determine whether it had any vulnerabilities, and I was displaying a warning if that were true. I'm now going with the far more performant (and useful) approach of just indicating if the version being displayed has one or more vulnerability.

2021-03-11 03:11 UTC, drewgillies commented
ping @joelverhagen :)

2021-03-11 20:26 UTC, joelverhagen commented on src/NuGetGallery/Services/PackageVulnerabilitiesService.cs
> +                throw new ArgumentNullException(nameof(package));
Should this throw if `VulnerablePackageRanges` is null? That would indicate it was not included in the EF query via `Include(...)`. It should be an empty list instead of null when there are no vulnerable ranges, right? In other words, I think it is strange to return `false` here if the user forgot to fetch VulnerablePackageRanges.

Or will this perform a lazy query if `Include` was not uses and `VulnerablePackageRanges` will never be null?

2021-03-11 20:27 UTC, joelverhagen approved these changes
Small question then :shipit:

2021-03-12 01:50 UTC, merged