Dg managepackages vulnerabilities
NuGet/NuGetGallery pull request #8436
Opened 2021-03-01 11:48 UTC by drewgillies

Note: this PR must be merged first: https://github.com/NuGet/NuGetGallery/pull/8435

Addresses remainder of https://github.com/NuGet/NuGetGallery/issues/8361

This change decorates all packages, of which the latest version is vulnerable, in the manage packages view with a bang and tooltip indicating to go to the details page.

2021-03-01 19:24 UTC, skofman1 commented on src/NuGetGallery/Controllers/UsersController.cs
>          public virtual ActionResult Packages()
we can get duration for this method in AI Requests table (like for all other requests). Don we need a special telemetry?

2021-03-01 23:07 UTC, drewgillies commented on src/NuGetGallery/Controllers/UsersController.cs
>          public virtual ActionResult Packages()
I think what I'll do is scope the telemetry in closer. @joelverhagen and I had discussed the value of specifically measuring perf for the query--I left the telemetry covering the whole method because I didn't know this about all endpoint methods getting duration metrics, and I expect the query is orders of magnitude costlier than other pieces here.

2021-03-02 01:26 UTC, loic-sharma commented on src/NuGetGallery/Controllers/UsersController.cs
> +            TelemetryService.TrackManagePackagesQueryPerformance(stopwatch.ElapsedMilliseconds, (listedPackages?.Count ?? 0) + unlistedPackages?.Count ?? 0);
Just curious, why do you use `listedPackages` and `unlistedPackages` here instead of `packages`?

2021-03-02 18:26 UTC, joelverhagen commented on src/NuGetGallery.Services/Telemetry/TelemetryService.cs
> +        public void TrackManagePackagesQueryPerformance(long milliseconds, int packageIdCount)
Nit: provide a `TimeSpan` to this method and map to ms/seconds/whatever as an implementation detail.

2021-03-02 18:27 UTC, joelverhagen commented on src/NuGetGallery/Controllers/UsersController.cs
>          public virtual ActionResult Packages()
An additionally telemetry event allows us to correlation duration to number of package IDs. The theory is that for owners with many packages this will be slower and slower. At least that's what I remember from our conversation 😄

2021-03-02 18:29 UTC, joelverhagen requested changes
It's unclear to me what the rollout strategy is and whether this implementation (+ dependency PR) will scale to authors with many packages. Could you provide a link to the design in the PR description if one exists?

2021-03-08 05:58 UTC, drewgillies commented on src/NuGetGallery/Controllers/UsersController.cs
>          public virtual ActionResult Packages()
You remember correctly, although the scenario was different. I was looping through entire sets of package versions to determine whether to show the vulnerability bang. This will slow down performance minimally. On reflection, with this in mind, I'll pull the telemetry for now.

2021-03-08 06:03 UTC, drewgillies commented on src/NuGetGallery/Controllers/UsersController.cs
> +            TelemetryService.TrackManagePackagesQueryPerformance(stopwatch.ElapsedMilliseconds, (listedPackages?.Count ?? 0) + unlistedPackages?.Count ?? 0);
They were separated in an earlier approach (with no `packages`) and this was a piece of cleanup I missed. Removed now though.

2021-03-08 06:15 UTC, drewgillies commented on src/NuGetGallery/Views/Users/Packages.cshtml
> +                            <i class="ms-Icon ms-Icon--Warning package-icon" data-bind="visible: IsVulnerable" title="This version has at least one known vulnerability. Details on package details pag
This is a tooltip, and there is a package link provided to the left. So, it's a good call, but probably needs just to be a change in wording for the tooltip, indicating to click on the package name, like this:
![image](https://user-images.githubusercontent.com/14225979/110282009-79c68580-8029-11eb-949d-59968d063ffd.png)

2021-03-08 06:16 UTC, drewgillies commented on src/NuGetGallery/Views/Users/Packages.cshtml
> +                            <i class="ms-Icon ms-Icon--Warning package-icon" data-bind="visible: IsVulnerable" title="This version has at least one known vulnerability. Details on package details pag
This is a tooltip, and there is a package link provided to the left. So, it's a good call, but probably needs just to be a change in wording for the tooltip, indicating to click on the package name, like this:
![image](https://user-images.githubusercontent.com/14225979/110282107-a4b0d980-8029-11eb-8ff7-ff75def30a79.png)

2021-03-08 06:18 UTC, drewgillies commented
> It's unclear to me what the rollout strategy is and whether this implementation (+ dependency PR) will scale to authors with many packages. Could you provide a link to the design in the PR description if one exists?

There's no reason to think there would be scaling issues. However, I'll do some deploy and measure testing. No specific engineering design document for this work exists as it's a single-field addition to a view model.

2021-03-09 22:53 UTC, drewgillies commented on src/NuGetGallery.Services/Telemetry/TelemetryService.cs
> +            public const string ManagePackagesQueryPerformance = "ManagePackagesQueryPerformance";
Telemetry is removed now.

2021-03-09 22:53 UTC, drewgillies commented on src/NuGetGallery.Services/Telemetry/TelemetryService.cs
> +        public void TrackManagePackagesQueryPerformance(long milliseconds, int packageIdCount)
Telemetry is removed now.

2021-03-11 03:11 UTC, drewgillies commented
ping @joelverhagen @loic-sharma :)

2021-03-11 20:32 UTC, joelverhagen approved these changes
It looks like there are changes from another PR in here and some merge conflicts, but the changes unique to this PR look good. Resolve branch issues then :shipit:

2021-03-12 02:13 UTC, merged