Dev
NuGet/NuGetGallery pull request #8447
Opened 2021-03-09 20:09 UTC by agr

2021-03-09 20:25 UTC, lyndaidaii commented
@agr, there is problem with uplod page with my changes(@lyndaidaii
Image allowlist (#8406) ) , here is fix here https://github.com/NuGet/NuGetGallery/pull/8443, Please merge after this fix go to dev

2021-03-09 21:59 UTC, joelverhagen approved these changes

2021-03-09 22:44 UTC, drewgillies approved these changes

2021-03-10 02:07 UTC, drewgillies requested changes
On reflection I think I'd like to get a feature flag in around this change before proceeding. Discussed offline.

2021-03-11 17:49 UTC, lyndaidaii approved these changes

2021-03-12 06:15 UTC, drewgillies commented
The flags are in--we're good to go.

2021-03-12 06:15 UTC, drewgillies approved these changes

2021-03-18 22:24 UTC, dannyjdev approved these changes

2021-03-18 22:24 UTC, loic-sharma approved these changes

2021-03-22 22:39 UTC, skofman1 approved these changes

2021-03-23 00:32 UTC, merged