return backfill to order by date, batch size 1000
NuGet/NuGetGallery pull request #8510
Opened 2021-04-08 07:50 UTC by drewgillies

Backfill job was ordered in such a way as to not work with cursoring. There was a filtering condition removed which also needed to be reinstated. I also upped the batching size to 1000 for the TM backfill.

2021-04-08 20:05 UTC, joelverhagen commented on src/GalleryTools/Commands/BackfillCommand.cs
> +                    .Where(p => p.PackageStatusKey == PackageStatus.Available || p.PackageStatusKey == PackageStatus.Validating)
`Validating` packages won't be available in v3-flatcontainer. Could we stick to `PackageStatus.Available`?

2021-04-08 20:05 UTC, joelverhagen requested changes
Unsure about the validating packages addition.

2021-04-08 22:32 UTC, drewgillies commented on src/GalleryTools/Commands/BackfillCommand.cs
> +                    .Where(p => p.PackageStatusKey == PackageStatus.Available || p.PackageStatusKey == PackageStatus.Validating)
@joelverhagen Great insight. Thank you. Note that this is for all backfill jobs--this is the parent class.

2021-04-13 03:23 UTC, drewgillies commented
>Unsure about the validating packages addition.
@joelverhagen note that this is removed code that I reintroduced. It could be an implementation detail (i.e. a flag) set in the subclasses if we like, defaulting to false.

2021-04-13 16:16 UTC, joelverhagen commented on src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
> +            catch (Exception e)
We can catch a more specific exception here, right? I think it's a specific one that is caused by the bad portables.

2021-04-13 16:16 UTC, joelverhagen commented on src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
> +            catch (Exception e)
```suggestion
            catch
```
if we end up using a generic catch-all like the other places

2021-04-13 16:17 UTC, joelverhagen approved these changes
Try to catch a more specific exception if possible. But otherwise looks good.

2021-04-14 00:01 UTC, drewgillies commented on src/GalleryTools/Commands/BackfillTfmMetadataCommand.cs
> +            catch (Exception e)
It's a little generic--it's an `ArgumentException` which is why I opted for catching all. But I'm happy to make it explicit as exceptions not of this type will fall through and be logged, which could be useful.

2021-04-14 01:03 UTC, merged