add banner to display, upload, list package pages
NuGet/NuGetGallery pull request #8579
Opened 2021-05-12 19:17 UTC by lyndaidaii

Summary of the changes (in less than 80 characters):

before: banner only show on the home page

after: banner show on the home page as well as display package detail, list packages, upload packages page

![displayp](https://user-images.githubusercontent.com/64443925/118031844-d3924700-b31b-11eb-90ca-f8108980ffb2.PNG)
![uploadpa](https://user-images.githubusercontent.com/64443925/118031851-d5f4a100-b31b-11eb-9aaa-c17d343faa1b.PNG)
![listpa](https://user-images.githubusercontent.com/64443925/118031858-d856fb00-b31b-11eb-897d-32af717885ef.PNG)

Addresses https://github.com/NuGet/NuGetGallery/issues/8525

2021-05-12 19:34 UTC, joelverhagen commented
Do we want it on all pages? How did we pick this specific set?

2021-05-12 19:39 UTC, lyndaidaii commented
> Do we want it on all pages? How did we pick this specific set?

yes, we want to it on all pages if this possible. the reason why pick those pages is it has high traffic to thoses pages, especially display package details pages. it has traffic from PMUI or google.

2021-05-12 22:47 UTC, joelverhagen commented on src/NuGetGallery/Views/Users/Packages.cshtml
> +    ViewBag.DisplayBanner = Model.DisplayBannerFeatureEnabled;
Can we do this in the Layout.cshtml + NuGetViewBase?

https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Views/Shared/Gallery/Layout.cshtml
https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/Views/NuGetViewBase.cs

This would hit every page.

2021-05-12 23:10 UTC, shishirx34 commented
Can we make this banner dismissable? It is very annoying to see it constantly for folks who don't care. It was tolerable when it was only on the home page but the user experience is terrible once we enable this on all pages. When asking for survey we should only ask it once when the page is opened after that allow it to be dismissable or it should auto-dismiss i.e. hide it after sometime if the user doesn't click on it, or say user logs in. Even if the user decides to respond to a survey why would we want to show the banner again.

2021-05-12 23:11 UTC, shishirx34 requested changes
I would avoid putting this on all pages, or at least redesign the banner to be dismissible.

2021-05-12 23:12 UTC, lyndaidaii commented on src/NuGetGallery/Views/Users/Packages.cshtml
> +    ViewBag.DisplayBanner = Model.DisplayBannerFeatureEnabled;
I am not sure about this approach. if we include in NuGetViewBase, which means flag for banner will be in the configure file instead of feature flag json file. let me know if my thinking is in right track?

2021-05-13 16:59 UTC, lyndaidaii commented
> I would avoid putting this on all pages, or at least redesign the banner to be dismissible.

The reason why we want add to most of pages is because of we are getting small amount of customer response this time comparing last time.

2021-05-13 17:42 UTC, jcjiang commented
@shishirx34 Some more context to not letting the banner be dismissed - the main reason why we decided to sidestep that functionality (for now) is because 1) saving the dismissed state for future sessions from the users would require additional engineering work that given the 2) relatively short windows - usually a week or two - during which the survey is out, might not be worth it.

Completely agree though that as we have surveys that are out for longer or are more visually distracting, we should allow the banner to be dismissed and/or not show on all pages.

2021-05-13 18:59 UTC, shishirx34 commented
@jcjiang - I disagree. Even the period of 1-2 weeks is too long of a period to showcase this anti-pattern. We get millions of views every week on the gallery. I've had personal experience with some users being annoyed when asked to give feedback for not using 2FA after login and this was a one time pop-up. I am certain lots of users will find this annoying. Being persistent and annoying at showing this banner to users just to get the feedback is not a good way to get the data, moreover, it disinclines the users to actually follow through. 

I remember that we had some form of survey (HATS?) where we had a "feedback" side rollout pop-up which was a much better way of getting feedback. This banner is pretty loud with a color scheme that doesn't really go with the site for continuous view and at the top of the page. Let's say a user does provide you with the feedback, we still continue to show this banner to that user which isn't a good user experience. I believe this banner was introduced for BLM support and now we are extending, probably misusing, it for survey purpose. 

We should either find a different way to get feedback, or at the very least invest engineering effort on making this dismissible so that it is reusable in the future. 

We should have a discussion offline if you still disagree.

/cc: @skofman1

2021-05-14 19:31 UTC, lyndaidaii commented
After discussion, we decide to display banner to all pages now due to reasons following:

- communication overhead with customers.  less confusion for customers since survey banner is always alive
- the reason why we are getting low response is not clear, we will investigate more, improve experience after getting more feedback from customers
- dismissble button requires some details info(how long banner will be dismiss), more time is required, which potentially make some annoying time for customers

We will add dismissible button for next NuGet.org survey to improve customer experience.

2021-05-14 22:26 UTC, shishirx34 approved these changes

2021-05-16 00:41 UTC, zhhyu commented on src/NuGetGallery/Controllers/AppController.cs
> +        private IFeatureFlagService _featureFalgService;
_featureFalgService -> _featureFlagService

2021-05-16 00:44 UTC, zhhyu commented on tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
> +                featureFlagsService.Setup(e => e.IsDisplayBannerEnabled()).Returns(false);
It's better to have a separate test for the banner flag.

2021-05-17 19:04 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
> +                Assert.False(controller.ViewBag.CanWriteAnalyticsCookies);
Why assert on analytics cookies? There is already a UT up there to do the same.

2021-05-17 19:04 UTC, joelverhagen approved these changes
Please limit UT assertions to only describe the UT name, i.e. the name of the "fact".
:shipit:

2021-05-17 20:49 UTC, zhhyu commented on tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
> +                featureFlagsService.Setup(e => e.IsDisplayBannerEnabled()).Returns(false);
There is no need to verify the banner flag in these two tests for cookies, if we have another test to cover it.

2021-05-17 20:58 UTC, zhhyu commented on tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
> +                cookieExpirationService.Setup(e => e.ExpireAnalyticsCookies(It.IsAny<HttpContextBase>()));
You can also remove this setup and verification because you test the banner flag here.

2021-05-17 20:59 UTC, zhhyu approved these changes

2021-05-18 06:44 UTC, lyndaidaii commented on tests/NuGetGallery.Facts/Controllers/AppControllerFacts.cs
> +                cookieExpirationService.Setup(e => e.ExpireAnalyticsCookies(It.IsAny<HttpContextBase>()));
it's private method. I don't think we could remove the set up

2021-05-18 07:07 UTC, merged