Table style with background
NuGet/NuGetGallery pull request #8914
Opened 2021-12-28 20:02 UTC by lyndaidaii

Summary of the changes (in less than 80 characters):

Make table pretty similar to Github table style:

upload preview page: 
![readmeupload](https://user-images.githubusercontent.com/64443925/147602779-005668bc-edcf-4ed1-b51d-ea31fdce85e9.png)
manage page: 
![readmeManage](https://user-images.githubusercontent.com/64443925/147602790-9a04ce0b-b5ce-4d31-af8d-100776cc68dd.png)
package detail page: 
![readmeShow](https://user-images.githubusercontent.com/64443925/147602794-0ca753be-0426-4201-900e-6a9cac136161.png)

Addresses:

2021-12-28 20:21 UTC, loic-sharma commented
Would you mind taking some screenshots of real READMEs with tables from GitHub? 

Here's a list of popular C# projects whose READMEs contain a table: https://github.com/loic-sharma/readme-experiments/blob/main/reports/tables.csv

Here are some READMEs on DEV:

* [Roslyn](https://dev.nugettest.org/packages/loic.dotnet.roslyn?preview=1#show-readme-container)
* [eShopOnContainers](https://dev.nugettest.org/packages/loic.dotnet-architecture.eShopOnContainers?preview=1#show-readme-container)
* [PowerToys](https://dev.nugettest.org/packages/loic.microsoft.PowerToys?preview=1#show-readme-container)

2022-01-03 17:43 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +    > thead,
Do we need to really specify thead/tbody/tfoot? something like `td, th` under `.table` should be enough right?

Do we need the border on the `table` element or can we just have it on the cells?

2022-01-03 17:44 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +  .table {
Why is this copied from above? Can we somehow unify the styles?

2022-01-03 17:44 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
> +            public void ConvertsMarkdownToHtmlWithImageDisaplyed(bool isMarkdigMdRenderingEnabled, string expectedHtml)
```suggestion
            public void ConvertsMarkdownToHtmlWithImageDisplayed(bool isMarkdigMdRenderingEnabled, string expectedHtml)
```

2022-01-03 17:46 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
> +            public void ConvertsMarkdownToHtmlWithImageDisaplyed(bool isMarkdigMdRenderingEnabled, string expectedHtml)
What's this img-fluid? I don't see this style in the Bootstrap 3 docs.

2022-01-03 17:46 UTC, joelverhagen requested changes
Just have a couple of small questions. The look n' feel looks great!

2022-01-03 17:56 UTC, lyndaidaii commented on tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
> +            public void ConvertsMarkdownToHtmlWithImageDisaplyed(bool isMarkdigMdRenderingEnabled, string expectedHtml)
it was 'img-responsive' in Bootstrap3, and they changed to 'img-fluid' in Bootstrap4. When we add Bootstrap extension in Markdig, it supports add table class to table, blockquote class, figure class , and add img-fluid class to all images links <img>(https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/BootstrapSpecs.md)
'img-fluid' won't be effective in bootstrap3, it was kind of redundant unless we update to bootstrap4.

2022-01-03 18:25 UTC, lyndaidaii commented on src/Bootstrap/less/theme/common-readme.less
> +  .table {
One is in preview read me on upload page and manage package page,  another one is in display page. since we defined the table style general. this table style was different from table for package version table. Not sure if we have a good way to unify the styles. any idea or suggestion?

2022-01-03 18:41 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +  .table {
We could introduce a new parent class to use in both places, and then make that the parent-most selector in the LESS file. Would that work?

2022-01-03 18:43 UTC, joelverhagen commented on tests/NuGetGallery.Facts/Services/MarkdownServiceFacts.cs
> +            public void ConvertsMarkdownToHtmlWithImageDisaplyed(bool isMarkdigMdRenderingEnabled, string expectedHtml)
I see. Since img-fluid doesn't work in Bootstrap 3, will images work okay in tables? 
https://getbootstrap.com/docs/4.0/content/images/#responsive-images
Perhaps we need to add the `img-fluid` class to our LESS so that images work similarly in tables? It might be worth testing very large images in tables to and compare the GitHub vs. behavior in this PR.

2022-01-12 22:03 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/DisplayPackageV2.cshtml
> +                            <div id= "readme-common">
```suggestion
                            <div id="readme-common">
```

2022-01-12 22:05 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +#readme-common{
This could really be a class, e.g. `.readme-common`. IMO it's best to use classes by default and only use IDs when you plan on writing code (e.g. DOM selectors in JS) to find that element. This seems like purely a "view"/display concern so class should be fine.

2022-01-12 22:06 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/_ImportReadMe.cshtml
> +        <div id = "readme-common">
```suggestion
        <div id="readme-common">
```

No spaces around attribute `=` sign is more idiomatic.

2022-01-12 23:02 UTC, loic-sharma commented on src/Bootstrap/dist/js/bootstrap.js
> + * Copyright 2011-2022 Twitter, Inc.
Just curious, why was this date updated?

2022-01-12 23:03 UTC, loic-sharma commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                    <div id= "readme-common">
```suggestion
                    <div id="readme-common">

```

2022-01-12 23:05 UTC, lyndaidaii commented on src/Bootstrap/dist/js/bootstrap.js
> + * Copyright 2011-2022 Twitter, Inc.
it was automatically updated when I ran 'grunt' I believe

2022-01-13 01:59 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +  img, .img-fluid{
should this be `img.img-fluid`? This would make the style only apply to images with `the .img-fluid` class, not all images.

2022-01-24 20:43 UTC, joelverhagen commented on src/Bootstrap/less/theme/common-readme.less
> +  img, img.img-fluid{
Let's leave a comment in here about why we need this class

2022-01-24 21:17 UTC, joelverhagen approved these changes
Address comments then :shipit:.
Please get one more approval.

2022-01-26 01:38 UTC, loic-sharma commented on src/Bootstrap/less/theme/common-readme.less
> +  img.img-fluid{
```suggestion
  img.img-fluid {
```

2022-01-26 01:38 UTC, loic-sharma commented on src/Bootstrap/less/theme/common-readme.less
> +.readme-common{
```suggestion
.readme-common {
```

2022-01-26 01:38 UTC, loic-sharma approved these changes

2022-01-27 21:00 UTC, merged