Adds User's MFA status when an API key is created
NuGet/NuGetGallery pull request #8947
Opened 2022-01-19 23:58 UTC by advay26

Addresses https://github.com/NuGet/Engineering/issues/4179

- Created a new `WasCreatedSecurely` column in the Credentials table
- If a user's current session was Multi Factor Authenticated when creating an API key, the table logs a `True` in the `WasCreatedSecurely` column, and `False` otherwise
- Added unit tests (for the `False` case when a user isn't MFA'd, simply adapted an existing test)

2022-01-20 03:15 UTC, joelverhagen commented on src/NuGet.Services.Entities/Credential.cs
> +        public bool WasCreatedSecurely { get; set; }
This should be nullable (tri-state): secure, insecure, unknown = null (row was created prior to the app code being deploy).

2022-01-20 03:15 UTC, joelverhagen commented on src/NuGetGallery/Controllers/UsersController.cs
> +            newCredential.WasCreatedSecurely = User.WasMultiFactorAuthenticated();
Does this bug affect this value?
https://github.com/NuGet/Engineering/issues/4181

2022-01-20 03:17 UTC, joelverhagen requested changes
Small comments/questions.

2022-01-20 03:33 UTC, clairernovotny commented
Can we record the type of MFA for later use--the amr claim value: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#the-amr-claim

That will tell us the strength of the auth for later analysis and/or enforcement.

2022-01-20 22:22 UTC, shishirx34 commented on src/NuGetGallery/Controllers/UsersController.cs
> +            newCredential.WasCreatedSecurely = User.WasMultiFactorAuthenticated();
It should not. That bug is likely that we do not store the MFA for aad account upon creation in DB. The above value is drawn from the claims, which are set correctly, which is what you see on the accounts page for 2FA.

2022-01-20 22:36 UTC, shishirx34 commented
@clairernovotny - I agree that it would be great to have it, I think for this PR it is a little out of scope. Currently we rely on the ACR claim to know if the MFA was used or not and the AMR claims are not yet plugged into our authentication session.

2022-01-20 22:37 UTC, shishirx34 commented on src/NuGet.Services.Entities/Credential.cs
> +        public bool WasCreatedSecurely { get; set; }
you might have to drop and recreate the migrations to get the default values updated in the local/dev DB.

2022-01-26 21:08 UTC, joelverhagen commented
> @clairernovotny Claire Novotny FTE - I agree that it would be great to have it, I think for this PR it is a little out of scope. Currently we rely on the ACR claim to know if the MFA was used or not and the AMR claims are not yet plugged into our authentication session.

Spoke with @clairernovotny offline. Let's proceed w/o the amr claim value. @clairernovotny feel free to open a NuGetGallery issue tracking this and surface it later when you see it fitting concretely into the rollout plan.

2022-02-01 23:16 UTC, advay26 commented on src/NuGet.Services.Entities/Credential.cs
> +        public bool WasCreatedSecurely { get; set; }
I made the field a nullable bool, so now entries that were created before the rollout of this feature will have NULL, while newer entries will have false/true based on their authentication.

2022-02-02 00:37 UTC, shishirx34 approved these changes

2022-02-02 03:09 UTC, joelverhagen approved these changes

2022-02-02 03:51 UTC, zhhyu approved these changes

2022-02-02 04:41 UTC, merged