Add reCAPTCHA to package uploads
NuGet/NuGetGallery pull request #8948
Opened 2022-01-21 06:55 UTC by drewgillies

Addresses: https://github.com/NuGet/Engineering/issues/4212

This change adds reCAPTCHA to the upload package flow. It's behind a feature flag with the disabled case attempting as little disruption as possible to existing logic. While a lot of time has been spent on this aspect, this is a good thing to double-check in this review.

Note that the HTML change in the _VerifyForm partial (`submit-package-template` insertion code) is largely indentation in the no-flag scenario. The only real change is the inclusion of the script which sets the RecaptchaEnabled JS var to false. I've duplicated this code for the enabled case to make it cleaner.

The creative piece here is the attachment of a delegate function to OnVerifySubmit in JS, which is the callback for reCAPTCHA, along with the globally scoped RecaptchaEnabled var which we set from the Razor view based on the view model's exposure of the feature flag value.

I've also opted to not turn on reCAPTCHA for symbols uploads as (1) it's customer noise, and (2) it's not a spam scenario.

I've tested the disabled and enabled scenarios numerous times, as well as the enabled + reCAPTCHA passing and enabled + reCAPTCHA failing (see image) scenarios. All seems to operate as expected.

reCAPTCHA in action:
![image](https://user-images.githubusercontent.com/14225979/150480405-af412293-0988-49e0-92f2-bbbc3f9ed58a.png)

Failing reCAPTCHA:
![image](https://user-images.githubusercontent.com/14225979/150480191-758bcab5-f635-49d9-bca9-dfd53c94f0da.png)

Browse button--no verify template, therefore no reCAPTCHA client yet:
![image](https://user-images.githubusercontent.com/14225979/150480606-91ea1b35-7275-41c3-b58e-efadf946a4a3.png)

Verify template inflated--reCAPTCHA client activated:
![image](https://user-images.githubusercontent.com/14225979/150480743-85baf15f-7a6a-48a5-9479-b9568fea4a3a.png)

2022-01-21 20:33 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
> +        <script type="text/javascript">RecaptchaEnabled = true;</script>
Correct me if I am wrong here, but since the `RecaptchaEnabled` value is set on the client side and the server side (`ValidateRecaptchaResponseForUploadsAttribute`) does not check the feature flag, a bot could override the request body to have `RecaptchaEnabled = true` and bypass reCAPTCHA, right?

2022-01-21 20:33 UTC, joelverhagen requested changes
I think we need server-side validation of the feature flag.

2022-01-24 01:25 UTC, drewgillies commented
@joelverhagen Makes sense. I've added a server side flag check.

2022-01-25 00:40 UTC, joelverhagen commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            TempData[GalleryConstants.RecaptchaEnabled] = verifyRequest.RecaptchaEnabled ? "true" : "false";
`TempData` is persisted in the cookie us, right? If we toggle feature flag on then off, will the temp data value get replaced?

Can the user clear this session state selectively via some cookie fiddling?

2022-01-25 00:40 UTC, joelverhagen commented on src/NuGetGallery/Filters/ValidateRecaptchaResponseForUploadsAttribute.cs
> +            var recaptchaEnabledData = filterContext.Controller?.TempData?[GalleryConstants.RecaptchaEnabled] ?? string.Empty;
Can we just call the Feature Flag service directly here?

2022-01-25 03:25 UTC, drewgillies commented
@joelverhagen I think this is a better solution. I'm attaching a custom-built filter to the action in DI code. this gives us feature flag service access in the filter.

2022-01-25 03:48 UTC, joelverhagen approved these changes
LGTM. Please get one other review.

2022-01-25 03:57 UTC, drewgillies commented on src/NuGetGallery/Views/Packages/_VerifyForm.cshtml
> +        <script type="text/javascript">RecaptchaEnabled = true;</script>
Good call--server side feature flag checking should cover this now.

2022-01-25 04:34 UTC, ryuyu approved these changes

2022-01-25 05:10 UTC, merged