Create artifacts for sharing NuGetGallery.Services
NuGet/NuGetGallery pull request #8962
Opened 2022-01-27 07:13 UTC by drewgillies

I did a feasibility spike on getting this project's artifacts into a nupkg for broader use, and got it working using a nupkg stub workaround with built assets (the same approach used for the jobs projects in the same buildstep).

Note that using the `New-ProjectPackage` PS function for this was a dead end, as this project is not SDK-style (the projects in the repo that do use this function are all SDK-style). The msbuild error there is that the `path` target is not defined, and this target comes built in to SDK-style projects. Converting the Services project into an SDK-style project is also non-trivial as it turns out, so that can possibly be future work.

2022-01-27 21:27 UTC, joelverhagen commented
Legacy csproj should accept pack if you install this package:
https://github.com/NuGet/NuGet.Jobs/blob/f053ae12e6661d7741cb1e096903111c4734f5ef/src/NuGet.Jobs.Common/NuGet.Jobs.Common.csproj#L101-L105 (old version of NuGet.Jobs.Common prior to SDK proj move)
Pack in build.ps1 as proof:
https://github.com/NuGet/NuGet.Jobs/blob/f053ae12e6661d7741cb1e096903111c4734f5ef/build.ps1#L137-L145

2022-01-27 21:28 UTC, joelverhagen commented on src/NuGetGallery.Services/NuGetGallery.Services.nuspec
> +    <file src="bin\$configuration$\**\*.*" target="bin"/>
bin assets are not recognized by NuGet. This package would have no available assets.

2022-01-27 21:28 UTC, joelverhagen requested changes
We can use New-ProjectPackage with a dev dependency.

2022-05-06 07:24 UTC, drewgillies commented
@joelverhagen Okay, I've addressed these now (thanks again). The `Authors` property was required, and I made it consistent with another project, but I'll go ahead and change it (and the other) to something other than .NET Foundation if desired. Perhaps NuGet. Let me know and I'll reiterate,

2022-05-06 15:40 UTC, joelverhagen approved these changes

2022-05-06 21:32 UTC, merged