[Bug]Fix potential overflow of statistics values.
NuGet/NuGetGallery pull request #9128
Opened 2022-06-02 00:15 UTC by ryuyu

Add support for stats values up to max value of long.

2022-06-02 16:30 UTC, joelverhagen commented on src/NuGetGallery/ViewModels/UserProfileModel.cs
> +            TotalPackageDownloadCount = AllPackages.Sum(p => (p.TotalDownloadCount));
```suggestion
            TotalPackageDownloadCount = AllPackages.Sum(p => p.TotalDownloadCount);
```

2022-06-02 16:30 UTC, joelverhagen commented on src/NuGetGallery/Infrastructure/Lucene/LuceneSearchService.cs
> +            long downloadCount = Int64.Parse(doc.Get("DownloadCount"), CultureInfo.InvariantCulture);
```suggestion
            long downloadCount = long.Parse(doc.Get("DownloadCount"), CultureInfo.InvariantCulture);
```

2022-06-02 16:31 UTC, joelverhagen commented on src/NuGetGallery/Infrastructure/Lucene/LuceneSearchService.cs
> +            long versionDownloadCount = Int64.Parse(doc.Get("VersionDownloadCount"), CultureInfo.InvariantCulture);
```suggestion
            long versionDownloadCount = long.Parse(doc.Get("VersionDownloadCount"), CultureInfo.InvariantCulture);
```

2022-06-02 16:32 UTC, joelverhagen commented
Looks like the CI is failing. Could you take a look?

Also, what does the generated SQL look like for the migration `Up` method? You can generate it with `Update-Database -Script`.

2022-06-02 16:32 UTC, joelverhagen requested changes
Small comments

2022-06-02 19:10 UTC, agr approved these changes

2022-06-03 00:51 UTC, zhhyu commented
Should we consider manually placing an overflowed download count in DEV or INT and test whether anything may be broken (CI, Tests, Manual UI tests)?

2022-06-03 01:28 UTC, zhhyu commented
Also, should we have a better understanding about what will happen on DB side? It doesn't seem like a metadata change. Will it cause any on-site issues considering the scale?

2022-06-03 02:46 UTC, shishirx34 approved these changes

2022-06-09 15:03 UTC, joelverhagen submitted a review, later dismissed

2022-06-09 18:56 UTC, dannyjdev commented on tests/NuGetGallery.Facts/ViewModels/UserProfileModelFacts.cs
> +                }, currentUser: null);;
nit: remove the last non needed `;`.

2022-06-09 21:55 UTC, ryuyu commented
> Also, should we have a better understanding about what will happen on DB side? It doesn't seem like just a metadata change. Will it cause any on-site issues considering the scale?

This is a great concern. After testing this on DEV, I highly recommend we do the PROD transition on a weekend so that the index recreation can proceed at low traffic time (DEV migration, including rebuild, took about 8 minute). Note that there will be downtime between the migration and the deployment of the new gallery. During this time, any requests that hit the Download Count column will probably return 500 as the column is now too wide for the bits. This means we will need to coordinate the release of migration and gallery, and will likely need to leave a status message letting users know that there may be failures during this time while we migrate.

2022-06-09 21:56 UTC, ryuyu commented on tests/NuGetGallery.Facts/ViewModels/UserProfileModelFacts.cs
> +                }, currentUser: null);;
Fixed.

2022-06-10 22:16 UTC, ryuyu commented
> This migration looks like it might be DTU intensive. We should carefully planned the execution, perhaps at a non-peak time of day.
> 
> @advay26 + @ryuyu - consider holding off the dev to main merge for this PR.

Looks like the code is backwards compatible with either bitwidth in SQL. It should be safe to deploy code and run migration later during down time. Given this, I think it SHOULD be safe to merge, but I'm ok holding off if that is what we want to do @joelverhagen .

2022-06-10 22:21 UTC, joelverhagen approved these changes

2022-06-13 20:29 UTC, dannyjdev approved these changes

2022-06-15 05:52 UTC, joelverhagen commented
@ryuyu - is this ready to merge?

2022-06-15 18:27 UTC, zhhyu approved these changes

2022-06-15 20:41 UTC, merged