[2FA] Disable nuget.org password login
NuGet/NuGetGallery pull request #9141
Opened 2022-06-15 00:27 UTC by dannyjdev

### Changes
- `NuGetAccountPasswordLoginUnsupported` feature flag added.
- `Sign in using NuGet.org account` removed if feature flag is enabled.
- NuGet Password login shows an error if email is not in exception list and featured flag is enabled.

### Addresses
- https://github.com/NuGet/Engineering/issues/4234
- https://github.com/NuGet/Engineering/issues/4314

2022-06-17 00:21 UTC, joelverhagen commented on src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
> -using System.Collections.Generic;
We typically put System.* first in the usings

2022-06-17 00:22 UTC, joelverhagen commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            await _contentObjectService.Refresh();
Does this do a "force" refresh every time? I.e. does this negate the caching? Wondering if this is really needed.

2022-06-17 00:24 UTC, joelverhagen commented
Should the actions (perhaps just the first, in the flow) related to password recovery be blocked on the server side too?

2022-06-17 20:06 UTC, shishirx34 commented
Can you put a link to the Microsoft sign in page on the password login? Perhaps put the link in the yellow banner, so that users can click and go to MSA login.

2022-06-17 20:18 UTC, shishirx34 requested changes

2022-06-17 20:18 UTC, shishirx34 commented on src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
> +        public bool IsNuGetAccountPasswordLoginUnsupportedEnabled()
Perhaps consider naming this `IsNuGetAccountPasswordLoginSupportedEnabled` instead? Double negation causes confusion.

2022-06-17 20:18 UTC, shishirx34 commented on src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
> +            return _client.IsEnabled(NuGetAccountPasswordLoginUnsupportedFeatureName, defaultValue: false);
`NuGetAccountPasswordLoginSupportedFeatureName` - with default value to `true`.

2022-06-17 20:18 UTC, shishirx34 commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            await _contentObjectService.Refresh();
Isn't content object service refreshing in background?

2022-06-17 20:18 UTC, shishirx34 commented on src/NuGetGallery.Services/Configuration/LoginDiscontinuationConfiguration.cs
> +        public bool IsUserEmailOnExceptionsForEmailAddress(User user)
Since you are passing in the `User` object rename this function to `IsUserOnExceptionsList`

2022-06-17 20:18 UTC, shishirx34 commented on src/NuGetGallery/Views/Authentication/SignIn.cshtml
> +        if (!Model.IsNuGetAccountPasswordLoginUnsupported)
This is double negation... change this to `if (Model.IsNuGetAccountPasswordLoginSupported)`

2022-06-17 20:18 UTC, shishirx34 commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +            public async Task NuGetAccountUnsupportedWithPasswordUsedAndNotInExceptionListReturnsSignInFailure()
also add a test case with `PasswordLogin` disabled and user is on exceptions list and is able to login? Essentially `CanLogTheUserOnWithEmailAddress` test case with password login disabled (and user on exceptions list).

2022-06-17 21:26 UTC, agr commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +                var emailAddress = "test@email.com";
We probably shouldn't reference actual existing domains that we are not associated with in tests.

2022-06-29 20:40 UTC, dannyjdev commented on src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
> -using System.Collections.Generic;
Updated.

2022-06-29 20:40 UTC, dannyjdev commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            await _contentObjectService.Refresh();
I didn't see any actual refresh when testing, so I removed it.

2022-06-29 20:42 UTC, dannyjdev commented on src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
> +        public bool IsNuGetAccountPasswordLoginUnsupportedEnabled()
In fact I started this work using a "Supported" flag, but since I negate it almost everywhere I thought it would be confusing as well and name it in negative form, I reverted since I do think now it sounds less confusing to have it as `IsNuGetAccountPasswordLoginEnabled`.

2022-06-29 20:49 UTC, dannyjdev commented on src/NuGetGallery.Services/Configuration/LoginDiscontinuationConfiguration.cs
> +        public bool IsUserEmailOnExceptionsForEmailAddress(User user)
Updated.

2022-06-29 20:49 UTC, dannyjdev commented on src/NuGetGallery/Views/Authentication/SignIn.cshtml
> +        if (!Model.IsNuGetAccountPasswordLoginUnsupported)
Updated.

2022-06-29 21:17 UTC, shishirx34 commented on src/NuGetGallery/ViewModels/LogOnViewModel.cs
> +        public bool IsNuGetAccountPasswordLogin { get; set; }
nit: `IsNuGetAccountPasswordLoginEnabled`

2022-07-01 21:09 UTC, dannyjdev commented on src/NuGetGallery/ViewModels/LogOnViewModel.cs
> +        public bool IsNuGetAccountPasswordLogin { get; set; }
Updated.

2022-07-01 21:10 UTC, dannyjdev commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +                var emailAddress = "test@email.com";
changed to `@example.com`, we don't own it but it's totally fine to use.

2022-07-01 21:10 UTC, dannyjdev commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +            public async Task NuGetAccountUnsupportedWithPasswordUsedAndNotInExceptionListReturnsSignInFailure()
Added test for those cases.

2022-07-08 19:22 UTC, agr commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            if (!_featureFlagService.IsNuGetAccountPasswordLoginEnabled() &&
Should this be the first check after input validation in this function? I.e. why do we authenticate then reject if password auth is disabled? Shouldn't we bail before even trying to authenticate? What response will the user get if supplied password is wrong?

2022-07-08 19:24 UTC, agr commented on src/NuGetGallery/Strings.resx
> +    <value>Forgot password has been disabled. Please reach out to your Microsoft account support to sign into NuGet gallery.</value>
> Forgot password has been disabled.

Sounds like it's missing a word. "Forgot password flow has been disabled"? "Forgot password process has been disabled"? Something else?

2022-07-08 21:59 UTC, dannyjdev commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            if (!_featureFlagService.IsNuGetAccountPasswordLoginEnabled() &&
I think this validation could be added before the authentication, but I thought it would be easier to understand if I add it later and reuse Credentials/User methods for password and email standardization and validation.

2022-07-08 22:01 UTC, dannyjdev commented on src/NuGetGallery/Strings.resx
> +    <value>Forgot password has been disabled. Please reach out to your Microsoft account support to sign into NuGet gallery.</value>
Updated.

2022-07-11 19:33 UTC, shishirx34 commented on src/NuGetGallery/Controllers/AuthenticationController.cs
> +            if (!_featureFlagService.IsNuGetAccountPasswordLoginEnabled() &&
Agree with @agr - this should be before the authentication. It will also reduce unnecessary SQL queries. You can check for `model.SignIn.UsernameOrEmail` to be on exception list and then proceed with authentication. It is a bit confusing since we only have emails for exceptions list and not usernames, but given that this flow is explicitly for our own convenience we can leave it at that. Consider adding a comment about it.

2022-07-11 19:41 UTC, shishirx34 commented on src/NuGetGallery/Controllers/UsersController.cs
> +            if(!_featureFlagService.IsNuGetAccountPasswordLoginEnabled())
Should we allow users on exceptions list to perform `ForgotPassword` scenario as well?

2022-07-11 22:20 UTC, joelverhagen commented on src/NuGetGallery/Controllers/UsersController.cs
> +            if(!_featureFlagService.IsNuGetAccountPasswordLoginEnabled())
We probably should, just in case we lose the password to the E2E test user :)

2022-07-14 05:57 UTC, drewgillies commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +                    .Verifiable();
These `Verifiable` calls may be superfluous, if you're only using `VerifyAll` rather than testing specifics like number of calls. `VerifyAll` should throw if any `Setup`ed method isn't called.

2022-07-14 05:58 UTC, drewgillies commented on tests/NuGetGallery.Facts/Controllers/AuthenticationControllerFacts.cs
> +                    .Verifiable();
Same here--I expect it will work fine without `Verifiable` on these.

2022-07-14 06:01 UTC, drewgillies commented
LGTM except for a couple nits (and resolving other comments).

2022-07-27 20:22 UTC, agr approved these changes

2022-07-27 21:45 UTC, shishirx34 approved these changes

2022-07-27 21:45 UTC, shishirx34 commented on src/NuGetGallery/Views/Authentication/_SignIn.cshtml
> +    }
I don't think it makes much sense in hiding this link, since the "Sign in with NuGet.org" page itself won't be visible to many people right? So not many folks are going to be able to reach here. In any case for users that are on exceptions list, who can perform forgot password flow or password logins, won't be able to see this link.

2022-07-27 22:14 UTC, dannyjdev commented on src/NuGetGallery/Views/Authentication/_SignIn.cshtml
> +    }
Nice catch, updated.

2022-07-27 22:16 UTC, shishirx34 approved these changes

2022-08-01 20:54 UTC, joelverhagen approved these changes

2022-08-01 20:58 UTC, merged