[A11y][ScreenReader] Prevent Screen Reader from reading non-header elements
NuGet/NuGetGallery pull request #9181
Opened 2022-07-28 21:59 UTC by camigthompson

Prevent the 'Prefix Reserved' element on a package page from being read when using the 'H' option in the screen reader by setting the element's `aria-hidden` attribute to `true`.

Current Behavior:
![nvda text original](https://user-images.githubusercontent.com/25823466/181644313-8fffa215-639e-4259-a230-88d89bc0686f.jpg)

New Behavior:
![nvda text edited](https://user-images.githubusercontent.com/25823466/181644345-d90c0f02-1423-47ca-b6c7-b358c192b887.png)

Addresses https://github.com/NuGet/NuGetGallery/issues/9173

2022-07-28 22:02 UTC, camigthompson commented
@ryuyu Is this the behavior we are looking for? The screen reader will now ignore the Prefix Reserved element when using the 'H' option but will also ignore the same element in all cases. Do we want this element to be accessible by the screen reader in cases other than when using the 'H' option?

2022-08-02 18:33 UTC, ryuyu commented
I think while this is the correct behaviour for this particular interaction, I think this will also cause the Prefix reserved marker to get ignored even if tabbed to specifically or selected in some way. What happens when we instead move the Prefix Reserved marker outside of the H1 tag? I THINK this should have a similar effect while leaving the accessibility of the icon untouched. We can give the block that contains it a specific new class and use the styling to position it if it looks wonky.

2022-08-02 18:33 UTC, ryuyu commented on src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
> +    ViewBag.BlockSearchEngineIndexing = true;
Is this related to the screen reader change?

2022-08-04 17:38 UTC, shishirx34 commented
@ryuyu / @camigthompson - does this PR need to be open against `main` branch? Is this a hotfix? If not, please rebase against `dev` branch.

2022-08-04 17:40 UTC, shishirx34 commented on src/NuGetGallery/Views/Packages/ReportAbuse.cshtml
> +    ViewBag.BlockSearchEngineIndexing = true;
This is spam mitigation change, I believe it was merged previously in `dev` branch. @camigthompson - please rebase this PR against `dev` branch instead of `main`

2022-08-04 21:22 UTC, camigthompson commented
> @ryuyu Peter Yu FTE / @camigthompson Camila Thompson FTE - does this PR need to be open against `main` branch? Is this a hotfix? If not, please rebase against `dev` branch.

Yes, that was my mistake. It should be fixed now.

2022-08-04 21:28 UTC, ryuyu approved these changes

2022-08-04 21:30 UTC, ryuyu requested changes
Clicked wrong thing by mistake! Sorry. Can we try moving this whole item outside of the header and check how it behaves? Thanks!

2022-08-10 21:17 UTC, lyndaidaii commented on src/Bootstrap/dist/css/bootstrap-theme.css
> -.page-package-details .package-title h1 .prefix-reserve-title {
we compile less file to generate css file, wondering if there is less file related to it. If so, please check the less file as well.

2022-08-18 19:07 UTC, shishirx34 submitted a review, later dismissed

2022-08-26 19:26 UTC, joelverhagen commented on src/Bootstrap/less/theme/page-display-package.less
> +        display: inline;
Are these `display: inline` additions needed now that the reserved block is outside of the `h1`?

2022-08-26 19:58 UTC, camigthompson commented on src/Bootstrap/less/theme/page-display-package.less
> +        display: inline;
Good catch! Probably not. I'll remove those

2022-08-26 20:23 UTC, ryuyu approved these changes

2022-08-26 21:23 UTC, joelverhagen approved these changes

2022-08-26 21:25 UTC, shishirx34 commented
can we get this merged and deployed? The S360 is still flagging these issues.

2022-08-30 22:37 UTC, camigthompson commented
The original UI and behavior: (Prefix Reserved in line with heading and read out)
![nvda text original](https://user-images.githubusercontent.com/25823466/187555600-052997ef-f05d-4046-b707-d6b8c7f3a8f0.jpg)

The new UI and behavior: (Prefix Reserved below the heading and not read out)
![nvda text new](https://user-images.githubusercontent.com/25823466/187555621-def564ed-6104-4c8a-afe9-fb0f9d9686a1.jpeg)

2022-09-01 19:54 UTC, merged