Bumped NuGet packages in NuGetGallery.FunctionalTests
NuGet/NuGetGallery pull request #9198
Opened 2022-08-17 20:38 UTC by aseemsahoo

The versions of the NuGet packages in `NuGetGallery.FunctionalTests` solution have been updated.

2022-08-17 20:38 UTC, dnfgituser commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=9198) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=9198) before we can accept your contribution.<br/><br/>:x: aseemsahoo [sign now](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=9198)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/NuGetGallery?pullRequest=9198) it.</sub>

2022-08-22 14:26 UTC, joelverhagen commented
Thanks for the contribution @aseemsahoo! I'll run this through our CI and DEV environment to make sure everything is working as expected.

2022-08-22 14:31 UTC, joelverhagen commented
I've rebased this branch on latest `dev` since we merge all non-hotfixes into `dev` prior to `main`.

2022-08-22 16:04 UTC, joelverhagen commented on tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
> -      <Version>2.1.1</Version>
This appears to be causing this error when running functional tests:
```
Warning: Test Run deployment issue: The assembly or module 'Microsoft.Web.XmlTransform' directly or indirectly referenced by the test container 'd:\a\_work\1\s\tests\nugetgallery.webuitests.p2\bin\release\nugetgallery.webuitests.p2.dll' was not found.
```

2022-08-22 16:05 UTC, joelverhagen commented on tests/NuGetGallery.FunctionalTests.Core/NuGetGallery.FunctionalTests.Core.csproj
> -      <Version>2.1.1</Version>
Would it be possible to remove this direct dependency and just let `NuGet.Core` pull in the default version transitively?

2022-08-22 16:05 UTC, joelverhagen requested changes
The Microsoft.Web.Xdt update is causing problems.

2022-08-23 15:10 UTC, closed without merging