[README] Hotfix for section links 500 error
NuGet/NuGetGallery pull request #9233
Opened 2022-09-12 22:29 UTC by camigthompson

Added a hotfix for the 500 internal server error resulting from the added support for section links.

Addresses https://github.com/NuGet/NuGetGallery/issues/9226

2022-09-12 22:51 UTC, joelverhagen commented on src/NuGetGallery/Services/MarkdownService.cs
> +                                    if (!(linkInline.Url is null) && !linkInline.Url.StartsWith("#")) //allow internal section links
We should have UT covering this case, i.e. one that failed (threw an NRE exception) prior to the change and one that passes after.

2022-09-12 22:55 UTC, joelverhagen requested changes
UTs then ship-it.

2022-09-12 23:05 UTC, lyndaidaii submitted a review, later dismissed

2022-09-12 23:48 UTC, camigthompson commented
> UTs then ship-it.

unit tests added

2022-09-12 23:49 UTC, camigthompson commented on src/NuGetGallery/Services/MarkdownService.cs
> +                                    if (!(linkInline.Url is null) && !linkInline.Url.StartsWith("#")) //allow internal section links
added a unit test

2022-09-13 12:51 UTC, joelverhagen approved these changes

2022-09-13 16:23 UTC, lyndaidaii approved these changes

2022-09-14 01:09 UTC, zhhyu commented on src/NuGetGallery/Services/MarkdownService.cs
> +                                    if (!(linkInline.Url is null) && !linkInline.Url.StartsWith("#")) //allow internal section links
>is null [](http://example.com/codeflow?start=57&length=7)

It appears that we use "== null" everywhere in the codebase. So it may be better to keep it.

2022-09-14 01:10 UTC, zhhyu submitted a review, later dismissed

2022-09-16 17:47 UTC, camigthompson commented on src/NuGetGallery/Services/MarkdownService.cs
> +                                    if (!(linkInline.Url is null) && !linkInline.Url.StartsWith("#")) //allow internal section links
Yes! Absolutely. The check for null is so that we don't attempt to call `.StartsWith()` on a null object. This is what was causing the 500 errors for packages.

2022-09-16 18:27 UTC, joelverhagen approved these changes

2022-09-16 18:27 UTC, zhhyu approved these changes

2022-09-16 18:45 UTC, merged