UI cleanup
NuGet/NuGetGallery pull request #9281
Opened 2022-10-24 22:02 UTC by lyndaidaii

Summary of the changes (in less than 80 characters):

* Add warning when package without readme
* Reword warning when package without license, align with readme
* Display unnecessary metadata when is not specified
* Upload collapse hide when there is metadata display in verify

**Additionally** UX is reviewed by UX team

Before: 
![Screenshot 2022-10-24 150028](https://user-images.githubusercontent.com/64443925/197638348-959e8db9-b673-4b8b-abcd-c2fd83e9dcc0.png)
After: 
![Screenshot 2022-10-24 145451](https://user-images.githubusercontent.com/64443925/197638062-fadb536d-05de-41f1-88c1-418e00751afe.png)

Addresses 

- [ ] https://github.com/NuGet/NuGetGallery/issues/9183
- [ ] https://github.com/NuGet/NuGetGallery/issues/9224
- [ ] https://github.com/NuGet/NuGetGallery/issues/9223

2022-10-25 15:20 UTC, joelverhagen commented
The new font on the warning message looks like a serif font. I don't think we use serif fonts anywhere on the site right now. Was this intentional?

The "How to include a license within the package." is written like a sentence but it's more a sentence fragment. Should it be an imperative like "See how ..."? 

cc @clairernovotny

2022-10-25 15:21 UTC, joelverhagen commented on src/NuGetGallery/Strings.resx
> +    <value>Readme missing. Go to https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#readme learn How to include a readme file within the package, or add it as yo
This is what will be included in the API push (CLI) message, right?

2022-10-25 15:21 UTC, joelverhagen commented on src/NuGetGallery/Strings.resx
> +  </data>
nit: remove trailing spaces

2022-10-25 15:22 UTC, joelverhagen commented on src/NuGetGallery/Strings.resx
> +    <value> License missing.</value>
there is a leading space at the beginning of the value. Intentional?

2022-10-25 15:24 UTC, joelverhagen commented
The gray "You had an upload in progress. You can continue here or cancel to restart seems a bit ugly and redundant. Do you think we can remove it? Or move it to the bottom near the cancel button? Just a thought.

2022-10-25 15:25 UTC, joelverhagen commented
What do you think about adding a feature flag for this?

2022-10-25 15:25 UTC, joelverhagen requested changes
I left some small comments and questions.

2022-10-25 18:45 UTC, lyndaidaii commented on src/NuGetGallery/Strings.resx
> +    <value>Readme missing. Go to https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#readme learn How to include a readme file within the package, or add it as yo
Yes, I will reword a little bit for API push message

2022-10-25 19:25 UTC, advay26 commented
> The new font on the warning message looks like a serif font. I don't think we use serif fonts anywhere on the site right now. Was this intentional?

The text for the individual Readme and License warnings also looks smaller than the surrounding text (in addition to being a different font). Even if we don't make them all use the same font, should we increase the font size for these warnings to make everything the same size?

![image](https://user-images.githubusercontent.com/82980589/197863533-f651add4-8b3d-4796-a81d-997268e306c8.png)

2022-10-25 23:44 UTC, lyndaidaii commented on src/NuGetGallery/Strings.resx
> +    <value> License missing.</value>
yes, this is Intentional, need one space with warning icon

2022-10-26 01:01 UTC, joelverhagen commented on src/NuGetGallery/Strings.resx
> +    <value> License missing.</value>
Consider putting it in the place that uses the string constant (call site) rather than in the string constant. Less likely to be "fixed" accidentally in the future.

2022-10-26 23:59 UTC, lyndaidaii commented
Added feature flag.

2022-10-27 02:34 UTC, lyndaidaii commented
CI push 
![Screenshot 2022-10-26 193344](https://user-images.githubusercontent.com/64443925/198177311-7884804e-0e8b-4c39-89e9-86e9a3d229f4.png)

2022-10-27 23:50 UTC, drewgillies approved these changes

2022-10-27 23:50 UTC, drewgillies commented on src/NuGetGallery/App_Data/Files/Content/flags.json
> +    "NuGetGallery.DisplayUploadWarningV2": {
Is there a reason we choose a flight over a flag here?

2022-10-31 16:14 UTC, lyndaidaii commented on src/NuGetGallery/App_Data/Files/Content/flags.json
> +    "NuGetGallery.DisplayUploadWarningV2": {
Flight could restrict to users specific.

2022-10-31 17:37 UTC, merged