Remove external privacy link
NuGet/NuGetGallery pull request #9347
Opened 2023-01-11 00:33 UTC by lyndaidaii

Redirect to https://www.nuget.org/policies/Privacy page instead of generic Microsoft privacy policy.

Addresses https://github.com/NuGet/NuGetGallery/issues/4469

2023-01-11 00:35 UTC, lyndaidaii commented on src/NuGetGallery/UrlHelperExtensions.cs
> -            if (!String.IsNullOrEmpty(_configuration.Current.ExternalPrivacyPolicyUrl))
Instead of deleting. I think comment out will be better since we have ExternalPrivacyPolicyUrl in configuration. 
otherwise, delete ExrternalPrivacyPolicyUrl configuration as well.

2023-01-11 17:18 UTC, joelverhagen commented on src/NuGetGallery/UrlHelperExtensions.cs
> -            if (!String.IsNullOrEmpty(_configuration.Current.ExternalPrivacyPolicyUrl))
I think this is the opposite of what we want. The currently linked privacy policy (the Microsoft shared one) is correct. The old privacy page however is still visible. I think the [privacy action](https://github.com/NuGet/NuGetGallery/blob/c1ccf24a931fb3e048e23c484f663580e906f30d/src/NuGetGallery/Controllers/PagesController.cs#L153) should redirect to `ExternalPrivacyPolicyUrl` when it's set.

2023-01-11 19:59 UTC, joelverhagen commented on src/NuGetGallery/Controllers/PagesController.cs
> +            if (!String.IsNullOrEmpty(Url.ExternalPrivacyUrl()))
UTs?

2023-01-11 21:07 UTC, lyndaidaii commented on src/NuGetGallery/Controllers/PagesController.cs
> +            if (!String.IsNullOrEmpty(Url.ExternalPrivacyUrl()))
??

2023-01-11 21:07 UTC, lyndaidaii commented on src/NuGetGallery/Controllers/PagesController.cs
> +            if (!String.IsNullOrEmpty(Url.ExternalPrivacyUrl()))
UTs stands for?

2023-01-11 21:17 UTC, joelverhagen commented on src/NuGetGallery/Controllers/PagesController.cs
> +            if (!String.IsNullOrEmpty(Url.ExternalPrivacyUrl()))
Apologies :) Unit tests.

2023-01-24 22:28 UTC, agr submitted a review, later dismissed

2023-01-24 22:29 UTC, agr commented
Please fix the link to the issue being addressed.

2023-01-24 22:29 UTC, agr commented on tests/NuGetGallery.Facts/UrlHelperExtensionsFacts.cs
> +        public class GetExternalPrivayUrlMethod : TestContainer
Class name typo.

2023-01-26 20:34 UTC, camigthompson requested changes
LGTM! Just need to fix the typo @agr mentioned

2023-02-02 19:04 UTC, lyndaidaii commented
> LGTM! Just need to fix the typo @agr mentioned

@camigthompson, could you take a look again?

2023-02-02 21:27 UTC, camigthompson approved these changes

2023-02-02 23:37 UTC, agr approved these changes

2023-02-02 23:48 UTC, merged