modify warning message on display package page when missing readme
NuGet/NuGetGallery pull request #9365
Opened 2023-02-01 00:36 UTC by lyndaidaii

Summary of the changes (in less than 80 characters):

* Introduced new warning message on package display page when package is missing readme
* only display warning message to package authors
* added feature flag to this new warning

Before: 
![Screenshot 2023-01-31 140711](https://user-images.githubusercontent.com/64443925/215915916-076f6854-e2da-48fb-8a73-6a8f8ddf11ed.png)
After: 
![Screenshot 2023-01-31 140647](https://user-images.githubusercontent.com/64443925/215915939-7573b301-73ad-4108-98c8-5b3a164070df.png)

Addresses https://github.com/NuGet/NuGetGallery/issues/123

2023-02-01 19:18 UTC, dannyjdev commented on src/NuGetGallery.Services/Configuration/FeatureFlagService.cs
> +        private const string DisplayPackageReadmeWarningFlightName = GalleryPrefix + "DisplayPackageReadmeWarning";
Add this prefix to the [flags.json file](https://github.com/NuGet/NuGetGallery/blob/main/src/NuGetGallery/App_Data/Files/Content/flags.json) with the default value you would like to have for local gallery.

2023-02-01 19:30 UTC, dannyjdev commented on src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
> +        bool IsDisplayPackageReadmeWarningEnabled(User user);
If you are not going to add particular users to this **Flight**, I would recommend to just create a **Flag** since those doesn't need the `User` parameter and can be just turned on and off.

2023-02-06 19:59 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                               style="@(Model.CanDisplayNewWarningWithoutReadme()? "background-color: #fff4ce": "background-color: #transparent")"
Typically we avoid inline CSS. Could you add a style for this (a class) and only add the class when the bool is true? This would also eliminate the need for the default `#transparent` case.

2023-02-06 20:00 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                                @ViewHelpers.AlertWarning(@<text>Your package is missing a README. Please update your package to <a href='https://aka.ms/nuget-include-readme'>include a README</a> or
We can instrument this link with a `data-track` attribute. Look for other places that do this. Then we can understand how many people click the link.

2023-02-06 20:00 UTC, joelverhagen requested changes
Some minor comments.

2023-02-07 19:05 UTC, lyndaidaii commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                                @ViewHelpers.AlertWarning(@<text>Your package is missing a README. Please update your package to <a href='https://aka.ms/nuget-include-readme'>include a README</a> or
nice, good to know. looks like data is tracked in AI?

2023-02-07 19:27 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                                @ViewHelpers.AlertWarning(@<text>Your package is missing a README. Please update your package to <a href='https://aka.ms/nuget-include-readme'>include a README</a> or
Yes, that's right. The App Insights JavaScript SDK receives the event and pushes it to the App Insights server-side. You can test is on DEV or even locally and see the event show up in App Insights in Azure Portal.

2023-02-07 20:24 UTC, lyndaidaii commented on src/NuGetGallery.Services/Configuration/IFeatureFlagService.cs
> +        bool IsDisplayPackageReadmeWarningEnabled(User user);
Thanks for notes. I think I will keep as it is. probably we want to add some certain users with this feature for testing. thanks!

2023-02-07 20:58 UTC, joelverhagen commented on src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
> +        public bool CanDisplayNewWarningWithoutReadme()
Why have both `CanDisplayNewWarningWithoutReadme` and `IsDisplayPackageReadmeWarningEnabled`? Should there just be one bool to check for both the warning icon and the warning text?

2023-02-07 20:59 UTC, joelverhagen commented on src/NuGetGallery/Views/Packages/DisplayPackage.cshtml
> +                            if (Model.CanDisplayPrivateMetadata & Model.IsDisplayPackageReadmeWarningEnabled)
Why use a bitwise `&`? `&&` is typically better since it has short circuiting and is consistent with other places.

2023-02-07 22:01 UTC, lyndaidaii commented on src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
> +        public bool CanDisplayNewWarningWithoutReadme()
not quite understand here. `CanDisplayNewWarningWithoutReadme` is checking feature flag and if package has readme or not.  Do you directly set up 'IsDisplayPackageReadmeWarningEnabled' with has readme condition?

2023-02-07 22:02 UTC, joelverhagen commented on src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
> +        public bool CanDisplayNewWarningWithoutReadme()
> Do you directly set up 'IsDisplayPackageReadmeWarningEnabled' with has readme condition?

Yes, that's what I mean. It could simplify the code, right?

2023-02-09 01:57 UTC, agr commented on src/NuGetGallery/ViewModels/DisplayPackageViewModel.cs
> +        public bool IsDisplayPackageReadmeWarningEnabled { get; set; }
The name is misleading. From the code below it seems the flag should indicate if readme warning should be displayed, not if that warning is enabled. How about just `DisplayReadmeWarning` or `ShouldDisplayReadmeWarning`?

2023-02-10 18:28 UTC, lyndaidaii commented
@dannyjdev, @joelverhagen, @agr , could you help take another look?  let me know need any change. thanks!

2023-02-13 17:36 UTC, joelverhagen approved these changes

2023-02-13 19:50 UTC, agr approved these changes

2023-02-13 19:54 UTC, merged