[2FA] Update link msa/aad account page with legacy password account information.
NuGet/NuGetGallery pull request #9408
Opened 2023-03-02 03:28 UTC by dannyjdev

### Changes
* Updated wording of the "Link Microsoft Account" page to include Legacy Account information.
* Removed **sign in** misleading inputs.

### Screenshot
![Legacy Account](https://user-images.githubusercontent.com/17834924/222323489-e101632a-49d0-4780-b529-e22cd5901a84.png)

Addresses: https://github.com/NuGet/Engineering/issues/4617

2023-03-02 13:54 UTC, joelverhagen commented on src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
> +                            <h1 class="text-center">Legacy Account</h1>
The wording seems good to me. Thoughts, @clairernovotny?

2023-03-02 13:56 UTC, joelverhagen requested changes
I left some comments on interaction with the allow-list.

2023-03-02 17:55 UTC, lyndaidaii commented on src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
> +                        @Html.ShowLabelFor(m => m.SignIn.UserNameOrEmail)<br />
I think might be better show email/username in the description above?  `We found an account with this email address('email address') ....` something like this?

2023-03-06 20:13 UTC, dannyjdev commented on src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
> +                        @Html.ShowLabelFor(m => m.SignIn.UserNameOrEmail)<br />
Updated with Lynn suggestion.

2023-03-08 01:48 UTC, dannyjdev commented on src/NuGetGallery/Views/Authentication/LinkExternal.cshtml
>      @if (Model.External.FoundExistingUser)
Updated.

2023-03-09 14:02 UTC, joelverhagen approved these changes

2023-03-10 00:00 UTC, merged