[D&V] Display deprecation and vulnerabilities on search page.
NuGet/NuGetGallery pull request #9440
Opened 2023-03-24 20:48 UTC by dannyjdev

### Changes
* Retrieve Deprecation and Vulnerabilities from Search Service.
* Added Deprecation and Vulnerabilities properties to Package.
* Display badges on search page.

### Screenshots

![Vulnerable and Deprecated](https://user-images.githubusercontent.com/17834924/227634254-474afdcb-d797-40a4-b978-6bd9f8209aec.png)

![Only Deprecated](https://user-images.githubusercontent.com/17834924/227634271-01930545-7689-4b72-9744-7f2c51d4708e.png)

![Only Vulnerable](https://user-images.githubusercontent.com/17834924/227634288-1fe3a617-b789-45cb-a361-57e915233031.png)

### Addresses
* https://github.com/NuGet/Engineering/issues/4734

2023-03-29 14:26 UTC, joelverhagen commented on src/NuGet.Services.Entities/Package.cs
> +        public Deprecation Deprecation { get; set; }
It feels a bit wrong to add new `[NotMapped]` properties this to the `Package` model for two reasons:

1. The data coming from the search service is a "service" layer concern while this entity is coupled with the persistence or data layer. These new properties and entities you added are couples with the search response shape not with the DB shape.
2. There are now two ways of expressing vulnerability information in the package. This could be very confusing for people using the `Package` entity. 

Would it be possible to populate the existing `Deprecations` and  `VulnerablePackageRanges` properties? This would align with the current approach of populating existing entity properties with data from the search service.

Unfortunately, this is all due to a poor design decision made in the past where the integration between the search service and the front-end search UI is done via a `Package` entity rather than directly mapping some API search response object to a Gallery search view model. I think it's out of scope to fix this problem and we should just adhere to the current approach of using `Package` as our intermediate object which gets mapped to the Razor view model.

2023-03-29 14:28 UTC, joelverhagen commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                                Vulnerable
Do you think there should be an additional `title` attribute or popover text explaining this is more detail? For example, something like sentence or sentences that align with the package details page?
![image](https://user-images.githubusercontent.com/94054/228570929-29dd433d-d9ef-46d1-b24b-19f5ce86309a.png)

2023-03-29 14:28 UTC, joelverhagen commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                                Deprecated
Similar to my comment above. Maybe a `title` attribute with more details could help. Maybe run it by PM or UX.

2023-03-29 14:29 UTC, joelverhagen requested changes
I'm concerned about the new `[NotMapped]` properties on the entities.

2023-03-30 00:41 UTC, drewgillies requested changes

2023-03-30 00:41 UTC, drewgillies commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                   }>@Html.BreakWord(Model.Id)</a>
Autoformatting has broken code consistency here.

2023-03-30 19:40 UTC, zhhyu commented on tests/NuGetGallery.Facts/Infrastructure/Lucene/ExternalSearchServiceFacts.cs
> +using System;
nit: system libraries as first ones

2023-03-31 01:54 UTC, zhhyu commented on src/Bootstrap/less/theme/common-list-packages.less
> +@badge-border-radius: 2px;
Is that better to share these css definitions with other components? Then there will be a more consistent appearance.

2023-04-03 07:37 UTC, dannyjdev commented on src/NuGet.Services.Entities/Package.cs
> +        public Deprecation Deprecation { get; set; }
I updated the code to use the current `Package` `Deprecations` and `VulnerablePackageRanges` properties.

2023-04-03 07:37 UTC, dannyjdev commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                   }>@Html.BreakWord(Model.Id)</a>
Reverted.

2023-04-03 07:38 UTC, dannyjdev commented on tests/NuGetGallery.Facts/Infrastructure/Lucene/ExternalSearchServiceFacts.cs
> +using System;
Updated.

2023-04-03 07:39 UTC, dannyjdev commented on src/Bootstrap/less/theme/common-list-packages.less
> +@badge-border-radius: 2px;
I think this could be done when we implement Dark Mode on nuget.org to know where to reuse and standardize our styles.

2023-04-03 21:59 UTC, theot12 reviewed
Looks good! I made some suggestions for the Deprecation Title.

2023-04-03 21:59 UTC, theot12 commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +                deprecationTitle += " is deprecated because it's legacy and no longer maintained";
```suggestion
                deprecationTitle += " is deprecated because it is no longer maintained.";
```

2023-04-03 21:59 UTC, theot12 commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +                deprecationTitle += " is deprecated";
```suggestion
                deprecationTitle += " is deprecated.";
```

2023-04-03 21:59 UTC, theot12 commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +            }
```suggestion
            if (hasCriticalBugs)
            {
                if (isLegacy)
                {
                    deprecationTitle += " is deprecated because it has critical bugs and is no longer maintained.";
                }
                else
                {
                    deprecationTitle += " is deprecated because it has critical bugs.";
                }
            }
```

2023-04-04 14:35 UTC, joelverhagen commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +    public class SearchResponseHelper
this can be a static class

2023-04-04 14:36 UTC, joelverhagen commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +    public class WarningTitleHelper
this can be a static class

2023-04-04 14:37 UTC, joelverhagen commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +        public static ICollection<PackageDeprecation> GetDeprecations(JToken docDeprecation)
Nit: call it `GetDeprecationsOrNull` to call out the fact that it's okay to return null.

2023-04-04 14:42 UTC, joelverhagen commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                            <span class="icon-text package-warning--vulnerable" aria-label="@Model.VulnerabilityTitle" data-content="@Model.VulnerabilityTitle">
If we use pop-overs here, make sure we don't have this problem:
https://github.com/NuGet/NuGetGallery/issues/9449

2023-04-05 01:30 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +            return deprecation == null ? null : new List<PackageDeprecation>() { deprecation };
On the Search Service if there are no valid deprecations the property is null, but for vulnerabilities is an empty array. I just wanted consistency on how we are getting those values. It's basically the same data we have in our indexes.

2023-04-05 03:35 UTC, joelverhagen commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +            return deprecation == null ? null : new List<PackageDeprecation>() { deprecation };
Sounds good, thanks.

2023-04-05 12:39 UTC, joelverhagen submitted a review, later dismissed

2023-04-05 12:40 UTC, joelverhagen commented on src/NuGetGallery/Views/Shared/_ListPackage.cshtml
> +                            <span class="icon-text package-warning--vulnerable" aria-label="@Model.VulnerabilityTitle" data-content="@Model.VulnerabilityTitle">
This might work automatically with the fix the @agr has already found (he mentioned it to me yesterday).

2023-04-06 21:31 UTC, dannyjdev commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +                deprecationTitle += " is deprecated because it's legacy and no longer maintained";
I liked removing legacy to have "is no longer maintained" since means the same. I updated the message.

2023-04-06 21:31 UTC, dannyjdev commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +                deprecationTitle += " is deprecated";
Message updated.

2023-04-06 21:32 UTC, dannyjdev commented on src/NuGetGallery/Helpers/WarningTitleHelper.cs
> +    public class WarningTitleHelper
Updated

2023-04-06 21:32 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +        public static ICollection<PackageDeprecation> GetDeprecations(JToken docDeprecation)
Updated.

2023-04-13 19:59 UTC, theot12 approved these changes

2023-04-21 15:30 UTC, joelverhagen submitted a review, later dismissed

2023-04-24 21:41 UTC, agr commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
Are ranges always not constrained on the end?

2023-04-24 21:42 UTC, agr commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
What if we decide to drop that space between `,` and `)` some day? Is there a reason not to search just for a comma?

2023-04-24 21:43 UTC, agr commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +        public static ICollection<PackageDeprecation> GetDeprecationsOrNull(JToken docDeprecation)
Should it be an extension method?

2023-04-24 21:53 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
Yes, it only have 2 values `[<version>, )` if it has a version or `*` when the version is empty or null..

2023-04-25 18:25 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +        public static ICollection<PackageDeprecation> GetDeprecationsOrNull(JToken docDeprecation)
It could be, but I don't have a strong preference either way.

2023-04-25 18:29 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
It's basically doing the inverse of the following line, [SearchDocumentBuilder.cs](https://github.com/NuGet/NuGet.Jobs/blob/main/src/NuGet.Services.AzureSearch/SearchDocumentBuilder.cs#L490). The format will need to change here if it changes on the other project.

2023-04-25 19:15 UTC, agr commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
My point is that if it changes there, your code might break. One way to make it less fragile is to just look for a comma instead of `, )` substring. It will not make it completely bulletproof, but at least would protect from a trivial change.

2023-04-25 19:19 UTC, theot12 submitted a review, later dismissed

2023-04-25 20:04 UTC, dannyjdev commented on src/NuGetGallery/Helpers/SearchResponseHelper.cs
> +                                version = range.Substring(1, range.IndexOf(", )"));
Updated.

2023-04-25 20:06 UTC, joelverhagen approved these changes

2023-04-26 00:11 UTC, merged