Add wakatime.com domain to whitelisted domains
NuGet/NuGetGallery pull request #9448
Opened 2023-04-03 07:29 UTC by guibranco

Addresses #9447

2023-04-03 07:30 UTC, guibranco commented
@dotnet-policy-service agree

2023-04-20 19:07 UTC, lyndaidaii commented
@guibranco, thanks for your contribution. We evaluated this domain, we decided to include it in our list.  Once CI is passed, I will go ahead and merge it into our dev branch. Thanks again!

2023-04-20 19:49 UTC, guibranco commented
Thanks @lyndaidaii

2023-04-20 19:50 UTC, lyndaidaii requested changes

2023-04-20 19:50 UTC, lyndaidaii commented on src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
> +        "wakatime.com"
@guibranco, could you put 'wakatime.com' order after travis-ci.org', it will keep as alphabetical order except for github domain on the bottom

2023-04-20 19:56 UTC, lyndaidaii commented on src/NuGetGallery/App_Data/Files/Content/Trusted-Image-Domains.json
> +        "wakatime.com"
Resolved. looks like my github has some issues. I didn't see my changes on this PR.

2023-04-20 19:56 UTC, lyndaidaii approved these changes

2023-04-20 20:33 UTC, merged