Remove empty variables from the URL
NuGet/NuGetGallery pull request #9537
Opened 2023-07-20 22:35 UTC by Lanaparezanin

Removed empty variables for packagetype, frameworks, and tfms from the URL.

Before: https://dev.nugettest.org/packages?q=net&packagetype=&frameworks=&tfms=&prerel=true&sortby=relevance
Now: https://localhost/packages?q=net&prerel=true&sortby=relevance

Addresses https://github.com/NuGet/NuGetGallery/issues/9373

2023-07-20 22:59 UTC, theot12 requested changes

2023-07-20 22:59 UTC, theot12 commented on src/NuGetGallery/Web.config
> +    <compilation debug="true" targetFramework="4.7.2">
This file should not be pushed. We definitely don't want to have `debug = true` in PROD.

2023-07-20 22:59 UTC, theot12 commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            if ((!isAdvancedSearchFlightEnabled || !searchService.SupportsAdvancedSearch) && false)
This will never return `true` and enter the `if` statement as is. Is this the expected behavior?

2023-07-20 23:00 UTC, lyndaidaii commented on src/NuGetGallery/Web.config
> +    <compilation debug="true" targetFramework="4.7.2">
Please remove this change since we only want debug = true in local dev environment.

2023-07-20 23:03 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            if ((!isAdvancedSearchFlightEnabled || !searchService.SupportsAdvancedSearch) && false)
&& false means this condition is always false. What is this trying to achieve?

2023-07-20 23:04 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            viewModel.IsAdvancedSearchFlightEnabled = true;
These 2 = true statements mean that the previous two lines are irrelevant (the value is overwritten). Why should these flights be set to true in every case?

2023-07-20 23:04 UTC, theot12 commented
One more thing: the destination branch should be 'dev'

2023-07-20 23:06 UTC, drewgillies commented on src/NuGetGallery/Scripts/gallery/page-list-packages.js
> +        frameworks.name = "";
Rather than using a proprty of frameworks for this, you could declare a separate variable for local use. Same in the below block.

2023-07-20 23:07 UTC, drewgillies commented on src/NuGetGallery/Scripts/gallery/page-list-packages.js
> +        frameworks.name = "";
Oh--this is to remove the text from the page? Maybe this is fine then.

2023-07-20 23:08 UTC, drewgillies commented on src/NuGetGallery/Web.config
> +    <compilation debug="true" targetFramework="4.7.2">
This change should be left out of the commit.

2023-07-20 23:37 UTC, advay26 commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            if ((!isAdvancedSearchFlightEnabled || !searchService.SupportsAdvancedSearch) && false)
I told Lana she could use this to bypass local feature flag settings that hide advanced search features during local development, but yes, these should be removed before the changes get merged in.

2023-07-20 23:39 UTC, advay26 commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            viewModel.IsAdvancedSearchFlightEnabled = true;
These statements were meant to bypass local feature flags so that advanced search could be tested locally, but they do need to be removed before the changes are merged into dev.

2023-07-20 23:54 UTC, dannyjdev commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            if ((!isAdvancedSearchFlightEnabled || !searchService.SupportsAdvancedSearch) && false)
To give some additional context on how these `FeatureFlags` work, is that you can enabled/disabled by using the [flags.json](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/App_Data/Files/Content/flags.json) so they shouldn't be always true. The flags are retrieved in code on [FeatureFlagService.cs](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery.Services/Configuration/FeatureFlagService.cs).

- `viewModel.IsFrameworkFilteringEnabled`: you can see it on this line that for local development is enabled for everyone [NuGetGallery/App_Data/Files/Content/flags.json#L118C5-L123C7](https://github.com/NuGet/NuGetGallery/blob/2f7b3947a81e464089bab86c330a13a7a276958b/src/NuGetGallery/App_Data/Files/Content/flags.json#L118C5-L123C7), on this case this variable doesn't need to be updated.

- `viewModel.IsAdvancedSearchFlightEnabled`: This one is tricky cause its assignment is from 2 variables
  -  `isAdvancedSearchFlightEnabled`: This is not on the `flags.json` file, you can add it at the `Flight` array like the following : `"NuGetGallery.AdvancedSearch": {
        "All": true,
        "SiteAdmins": false,
        "Accounts": [],
        "Domains": []
      }`
  -  There was a reason @advay26 this was left out?
  - `searchService.SupportsAdvancedSearch`: I think this is true when you setup the `Gallery.SearchServiceUriPrimary` variable on the [Web.config](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Web.config#L146) file.

2023-07-20 23:57 UTC, dannyjdev commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            viewModel.IsAdvancedSearchFlightEnabled = true;
To give some additional context on how these `FeatureFlags` work, is that you can enabled/disabled by using the [flags.json](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/App_Data/Files/Content/flags.json) so they shouldn't be always true. The flags are retrieved in code on [FeatureFlagService.cs](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery.Services/Configuration/FeatureFlagService.cs).

- `viewModel.IsFrameworkFilteringEnabled`: you can see it on this line that for local development is enabled for everyone [NuGetGallery/App_Data/Files/Content/flags.json#L118C5-L123C7](https://github.com/NuGet/NuGetGallery/blob/2f7b3947a81e464089bab86c330a13a7a276958b/src/NuGetGallery/App_Data/Files/Content/flags.json#L118C5-L123C7), on this case this variable doesn't need to be updated.

- `viewModel.IsAdvancedSearchFlightEnabled`: This one is tricky cause its assignment is from 2 variables
  -  `isAdvancedSearchFlightEnabled`: This is not on the `flags.json` file (There was a reason @advay26 this was left out?), you can add it at the `Flight` array like the following : `"NuGetGallery.AdvancedSearch": {
        "All": true,
        "SiteAdmins": false,
        "Accounts": [],
        "Domains": []
      }`
  - `searchService.SupportsAdvancedSearch`: I think this is true when you setup the `Gallery.SearchServiceUriPrimary` variable on the [Web.config](https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Web.config#L146) file.

2023-07-21 00:35 UTC, advay26 commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            viewModel.IsAdvancedSearchFlightEnabled = true;
@dannyjdev Thanks! I wasn't sure how to bypass the `searchService.SupportsAdvancedSearch` boolean when I was working on this earlier, so I chose this option. I'll use the Web.config variable in the future.

`"isAdvancedSearchFlightEnabled: This is not on the flags.json file (There was a reason @advay26 this was left out?)"`
I'm not sure. This variable was already around when I started working on the search page, so I didn't pay much attention to it at the time. I can create a tracking issue to look into it later and add it to the file.

2023-07-21 17:04 UTC, theot12 commented
Updated the destination branch to `dev`

2023-07-21 17:04 UTC, theot12 approved these changes
Looks great!

2023-07-21 17:42 UTC, lyndaidaii approved these changes

2023-07-21 18:23 UTC, advay26 approved these changes

2023-07-21 20:18 UTC, Lanaparezanin commented on src/NuGetGallery/Web.config
> +    <compilation debug="true" targetFramework="4.7.2">
Thanks for catching that, I removed it!

2023-07-21 20:29 UTC, merged