Azure AD Rebranding
NuGet/NuGetGallery pull request #9652
Opened 2023-09-06 20:08 UTC by Goodyear2017

Change "Azure AD" to "Microsoft Entra ID"

Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1869215

2023-09-06 21:01 UTC, erdembayar approved these changes

2023-09-07 16:07 UTC, mariaghiondea requested changes
Can you please remove "ID"? We only need to replace to "Microsoft Entra"

2023-09-07 16:10 UTC, mariaghiondea submitted a review, later dismissed

2023-09-07 22:34 UTC, mariaghiondea approved these changes

2023-09-20 15:14 UTC, joelverhagen approved these changes
I've queued a CI build. Let's see how that goes.

2023-09-20 16:14 UTC, merged