Pull GitHub for vulnerabilites out to library.
NuGet/NuGetGallery pull request #9657
Opened 2023-09-10 21:13 UTC by ryuyu

This is pre-requisite change to use this library for the larger coming job to update vulnerabilities files.
While the changes is large, the code is largely the same code that was already being used in the GitHubVulnerabilities2Db job.

2023-09-11 14:11 UTC, joelverhagen commented on src/NuGet.Services.Github/Class1.cs
> +﻿using System;
This looks like it can be deleted

2023-09-11 14:12 UTC, joelverhagen commented on NuGetGallery.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NuGet.Services.GitHub", "src\NuGet.Services.Github\NuGet.Services.GitHub.csproj", "{043645D5-129F-4BA1-BD17-77153294F2BD}"
nit: the project name has a lowercase `h` in `NuGet.Services.Github`. It should be uppercase. You'll need to do a git remove then add for it to work since case insensitive Windows paths and Git act weirdly.

2023-09-11 14:13 UTC, joelverhagen commented on src/NuGet.Services.Github/GraphQL/QueryService.cs
> +                _configuration.GitHubGraphQLQueryEndpoint = _defaultQueryUrl;
The default should live in the config class, not in the services that use the config. This shouldn't even be necessary with your default property value in `GraphQLQueryConfiguration` right?

2023-09-11 14:14 UTC, joelverhagen commented on src/NuGet.Services.Github/NuGet.Services.GitHub.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Yay, SDK style proj! Nice!

2023-09-11 14:14 UTC, joelverhagen commented on src/NuGet.Services.Github/NuGet.Services.GitHub.csproj
> +    <ProjectReference Include="..\NuGetGallery.Services\NuGetGallery.Services.csproj" />
I think the answer is yes, but do we indeed need this dependency over `NuGetGallery.Core`?

2023-09-11 14:15 UTC, joelverhagen commented on src/NuGet.Services.Github/Properties/AssemblyInfo.cs
> +﻿using System.Reflection;
Do we need this? This is automatically generated in SDK-style projects

2023-09-11 14:15 UTC, joelverhagen requested changes
Minor comments, looks like a good refactor overall. Thanks for having a dedicated PR for this.

2023-09-13 04:16 UTC, mariaghiondea commented
What testing was done to ensure no regressions?

2023-09-13 20:40 UTC, ryuyu commented on src/NuGet.Services.Github/GraphQL/QueryService.cs
> +                _configuration.GitHubGraphQLQueryEndpoint = _defaultQueryUrl;
That's correct. We don't need this due to the default in the config. I'll remove this block.

2023-09-13 20:41 UTC, ryuyu commented on src/NuGet.Services.Github/NuGet.Services.GitHub.csproj
> +    <ProjectReference Include="..\NuGet.Services.Entities\NuGet.Services.Entities.csproj" />
I would expect that, but I can't remember if it worked as expected. I'll remove it and see if we get the references transitively.

2023-09-13 20:41 UTC, ryuyu commented on src/NuGet.Services.Github/NuGet.Services.GitHub.csproj
> +    <ProjectReference Include="..\NuGetGallery.Services\NuGetGallery.Services.csproj" />
Yes we do need it. There was a service that was being used in I think the Ingestor that requires an interface available in services project.

2023-09-13 20:42 UTC, ryuyu commented on src/NuGet.Services.Github/Properties/AssemblyInfo.cs
> +﻿using System.Reflection;
When I made the switch, I think i didn't remove a lot of the now unnecessary usings. I'll do a pass.

2023-09-13 20:43 UTC, ryuyu commented on src/NuGet.Services.Github/Class1.cs
> +﻿using System;
I'll do a pass and get rid of the some of the usings that were made obsolete by SDK style.

2023-09-13 20:44 UTC, ryuyu commented on src/NuGet.Services.Github/Class1.cs
> +﻿using System;
I just realized you meant the whole file. Yes I'll remove it.

2023-09-13 20:47 UTC, ryuyu commented
> What testing was done to ensure no regressions?

There is a series of test in the repository that were run and found passing. Ran locally and everything appeared to work.

2023-09-13 20:47 UTC, ryuyu commented on src/NuGet.Services.Github/Properties/AssemblyInfo.cs
> +﻿using System.Reflection;
Ah you mean the whole file. I'll dump it and see if still works.

2023-09-13 21:03 UTC, ryuyu commented on NuGetGallery.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NuGet.Services.GitHub", "src\NuGet.Services.Github\NuGet.Services.GitHub.csproj", "{043645D5-129F-4BA1-BD17-77153294F2BD}"
I think I fixed it? It looks fixed to me, but would like a confirmation that it looks fixed from another view.

2023-10-03 00:16 UTC, agr commented on src/NuGet.Services.Github/Collector/AdvisoryQueryBuilder.cs
> +    public class AdvisoryQueryBuilder : IAdvisoryQueryBuilder
Is this new code? Is it covered by tests?

2023-10-03 00:18 UTC, agr commented on src/NuGet.Services.Github/Collector/AdvisoryQueryService.cs
> +            return await Task.WhenAll(advisories.Select(a => FetchAllVulnerabilitiesAsync(a, token)));
Do we want to limit the concurrency here? Otherwise at the very least we have a potential of hammering GH with large number of parallel requests.

2023-10-03 00:26 UTC, agr commented on src/NuGet.Services.Github/Ingest/AdvisoryIngestor.cs
> +        private Tuple<PackageVulnerability, bool> FromAdvisory(SecurityAdvisory advisory)
Could we use tuple with named fields as a return type here?
```
private (PackageVulnerability vulnerability, bool withdrawn) FromAdvisory(SecurityAdvisory advisory)
```

2023-10-03 00:29 UTC, agr commented on src/NuGet.Services.Github/Ingest/GitHubVersionRangeParser.cs
> +                if (versionRangeParts.Length <= i + 1)
We can check that the length is even right after split once, right? No need to check it in the loop over and over again.

2023-10-03 00:31 UTC, agr commented on src/NuGet.Services.Github/Ingest/GitHubVersionRangeParser.cs
> +            var versionRangeParts = gitHubVersionRangeWithoutCommas.Split(' ');
It seems to assume there is always a space between "a symbol" and "a SemVer version". Is it really the case?

2023-10-05 22:42 UTC, ryuyu commented on src/NuGet.Services.Github/Collector/AdvisoryQueryBuilder.cs
> +    public class AdvisoryQueryBuilder : IAdvisoryQueryBuilder
There should be no new content in this refactor. I believe this class existed before inside the GithubVulnerabilities2Db job.

2023-10-05 22:43 UTC, ryuyu commented on src/NuGet.Services.Github/Collector/AdvisoryQueryService.cs
> +            return await Task.WhenAll(advisories.Select(a => FetchAllVulnerabilitiesAsync(a, token)));
I'll keep this comment in mind and address the issue going forward. I want to make minimal functional changes in this PR to try to maintain parity.

2023-10-05 22:44 UTC, ryuyu commented on src/NuGet.Services.Github/Ingest/AdvisoryIngestor.cs
> +        private Tuple<PackageVulnerability, bool> FromAdvisory(SecurityAdvisory advisory)
Does this change functionality? Or is it purely a semantic change? If it's semantic only, I'm happy to make this change.

2023-10-05 22:45 UTC, ryuyu commented on src/NuGet.Services.Github/Ingest/GitHubVersionRangeParser.cs
> +                if (versionRangeParts.Length <= i + 1)
I'm not 100% sure what this code is doing. Again, I was trying to make minimal changes, but I'll look in to this one.

2023-10-05 22:46 UTC, ryuyu commented on src/NuGet.Services.Github/Ingest/GitHubVersionRangeParser.cs
> +            var versionRangeParts = gitHubVersionRangeWithoutCommas.Split(' ');
I believe this is the case. As far as I am aware, we have not yet observed any that don't follow this pattern.

2023-10-09 14:47 UTC, joelverhagen commented on src/NuGet.Services.GitHub/GraphQL/QueryService.cs
> +        public const string UserAgent = "NuGet.Jobs.NuGet.Services.GitHub";
This user agent seems a bit weird. Probably just `NuGet.Services.GitHub` is fine

2023-10-09 14:48 UTC, joelverhagen commented on src/NuGet.Services.GitHub/NuGet.Services.GitHub.csproj
> +      <Version>2.109.0</Version>
I believe this has a shared variable now
https://github.com/NuGet/NuGetGallery/blob/ece9a197bc8dc4f6a0f6519677a8bc2de8742572/Directory.Build.props#L4

2023-10-09 14:50 UTC, joelverhagen commented on src/NuGet.Services.Github/Collector/AdvisoryQueryService.cs
> +            return await Task.WhenAll(advisories.Select(a => FetchAllVulnerabilitiesAsync(a, token)));
There is duplicated content
![image](https://github.com/NuGet/NuGetGallery/assets/94054/42a50be4-1a90-4936-b409-1a7ae7e7f06a)
It appears that both path cases (Github and GitHub are present in the source tree)

2023-10-09 21:57 UTC, erdembayar commented on .github/dependabot.yml
> -#    - nuget/gallery-team
Is it expected change? Seems like not related.

2023-10-09 22:07 UTC, erdembayar commented on src/NuGet.Services.Github/Ingest/AdvisoryIngestor.cs
> +        private Tuple<PackageVulnerability, bool> FromAdvisory(SecurityAdvisory advisory)
If it's hot path then there's memory perf difference between `value` tuple vs `tuple`.  https://www.codeguru.com/csharp/c-sharp-valuetuple/#:~:text=Final%20Thoughts%20on%20ValueTuple%20in,and%20give%20them%20meaningful%20names.

```
One significant issue with the Tuple class is that it is a reference type allocated in the managed heap. Using it, developers might encounter CPU spikes and [garbage collection](https://www.webopedia.com/definitions/garbage-collection/) pressure – (i.e., substantial performance concerns). The ValueTuple, on the other hand, is a lightweight value-type object with stack memory.
```

2023-10-11 21:00 UTC, ryuyu commented on src/NuGet.Services.GitHub/GraphQL/QueryService.cs
> +        public const string UserAgent = "NuGet.Jobs.NuGet.Services.GitHub";
Agreed. Updated.

2023-10-11 21:03 UTC, ryuyu commented on src/NuGet.Services.GitHub/NuGet.Services.GitHub.csproj
> +      <Version>2.109.0</Version>
Rebased on dev to get this. Updated to use it.

2023-10-11 21:20 UTC, ryuyu commented on .github/dependabot.yml
> -#    - nuget/gallery-team
It was removed before, and i'm replicating it here since it breaks the build.

2023-10-11 21:20 UTC, ryuyu commented on .github/dependabot.yml
> -#    - nuget/gallery-team
MIght have gone away with the rebase on dev.

2023-10-13 19:06 UTC, agr commented on src/NuGet.Services.Github/Ingest/AdvisoryIngestor.cs
> +        private Tuple<PackageVulnerability, bool> FromAdvisory(SecurityAdvisory advisory)
> Does this change functionality?
No, the code that uses it will use names that are better than `Item1`. Like Erick mentioned there might be perf improvements, but I don't think we'll notice. However, we might not have the language support enabled.

2023-10-13 19:07 UTC, agr approved these changes

2023-10-13 19:09 UTC, joelverhagen approved these changes

2023-10-13 21:16 UTC, merged