Make older versions collapsible
NuGet/NuGetGallery pull request #9658
Opened 2023-09-11 21:16 UTC by Lanaparezanin

I made the older versions of the nuget Downloads page collapsible. When expanded, there should be a red message indicating that these versions are unsupported.

Testing: Go to [this file](https://github.com/NuGet/NuGet.Services.Index/blob/main/PROD/dist.nuget.org-index/index.json). Click on "raw" (see image)
<img width="118" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/0c3ecb8b-405d-4ac6-8847-821ed37baf76">

Copy the URL of the raw file. Now, go to Downloads.cshtml line 86 and instead of //dist.nuget.org/index.json, paste the URL you previously copied. Run the code. Go to Downloads. Older versions of win-x86 should be collapsible. There should also be a red message indicating that these versions are unsupported.

Addresses https://github.com/NuGet/Engineering/issues/4949

2023-09-12 04:24 UTC, mariaghiondea commented
@Lanaparezanin is it possible to see a screenshot or gif/movie of the experience?

2023-09-12 20:29 UTC, zhhyu commented on src/NuGetGallery/Scripts/gallery/jquery-3.4.1.js
> +    $(document).on('dataLoaded', function () {
This should not be the correct place to put these changes, under "jquery" library.

2023-09-12 21:03 UTC, zhhyu commented on src/NuGetGallery/Scripts/gallery/jquery-3.4.1.js
> +        const listContainer = document.getElementById('win-x86-versions').children[1];   //children[0] is the headline, children[1] is the list of versions
I suggest considering using jQuery APIs rather than plain JavaScript and align with other scripts.

2023-09-13 03:57 UTC, mariaghiondea commented
@ryuyu can you please review, especially from an accessibility standpoint?

2023-09-14 22:06 UTC, ryuyu commented
Fastpass is flagging a few issues with the "li" usage in the list, and the contrast of the red warning message.
![image](https://github.com/NuGet/NuGetGallery/assets/11051729/82035e3f-2227-417e-9946-96759369cc31)

Narrator reads out "collapsed" on the caret, even after expanding.
Narrator doesn't read out the red message at all.

I think we should address these things to avoid accessibility issues down the line.
Otherwise, looks great!

If you need to run the FastPass locally, there is a browser extension called Accessibility Insight for Web that you can install to Edge from https://microsoftedge.microsoft.com/addons/detail/accessibility-insights-fo/ghbhpcookfemncgoinjblecnilppimih?hl=en-US

2023-09-14 22:07 UTC, ryuyu requested changes
See above comment. I made it before submitting the review.

2023-09-24 01:29 UTC, erdembayar commented on src/NuGetGallery/Scripts/gallery/jquery-3.4.1.js
> +    $(document).on('dataLoaded', function () {
If you change this file then next time we're going to have hard time for patching and updating for new version.

2023-09-25 21:53 UTC, Lanaparezanin commented on src/NuGetGallery/Scripts/gallery/jquery-3.4.1.js
> +    $(document).on('dataLoaded', function () {
I moved the code from this file to a new page-downloads file, thanks for letting me know!

2023-09-25 23:11 UTC, Lanaparezanin commented
@ryuyu Thanks for pointing out the issues, they should all be fixed now: 

<img width="941" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/0a4c83c6-ea16-461a-a4a7-4cfb02e797de">

Also, I installed the screen reader and fixed the red text, it now reads everything.

2023-09-25 23:14 UTC, Lanaparezanin commented
@mariaghiondea  Here is a before and after:

Before:
<img width="900" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/79565d44-56b0-45d7-9dc3-a7b2a9e067cb">

After:
<img width="928" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/9035b7ef-de65-4dc4-86c5-f4fdf63fa917">

<img width="891" alt="image" src="https://github.com/NuGet/NuGetGallery/assets/58230697/67b1c95d-68a2-4232-a199-3f7fb3c01518">

2023-09-26 04:51 UTC, mariaghiondea approved these changes

2023-09-26 19:59 UTC, ryuyu approved these changes

2023-09-26 23:13 UTC, merged