Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault, next iteration
NuGet/NuGetGallery pull request #9661
Opened 2023-09-12 00:41 UTC by erdembayar

Related to: https://github.com/NuGet/Engineering/issues/4704

Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault package dependency. Former one is deprecated.
This one is separate from previously merged https://github.com/NuGet/NuGetGallery/pull/9654, we have to another round of update due to circular dependency in NuGet.Jobs (NuGetGallery -> NuGet.Jobs -> NuGetGallery).

2023-09-12 02:28 UTC, joelverhagen commented on src/AccountDeleter/AccountDeleter.csproj
> +      <Version>4.3.0-dev-8382474</Version>
Looks like a bad merge. Remove line 112

2023-09-12 02:28 UTC, joelverhagen requested changes
⌚ looks like duplicate Version elements

2023-09-12 04:05 UTC, erdembayar commented on src/AccountDeleter/AccountDeleter.csproj
> +      <Version>4.3.0-dev-8382474</Version>
Sorry, it was cherry-pick error, addressed.

2023-09-12 04:21 UTC, mariaghiondea approved these changes

2023-09-13 03:31 UTC, joelverhagen approved these changes

2023-09-13 03:43 UTC, merged