Reject POST to report abuse if the reason isn't one we allow reporting from the form.
NuGet/NuGetGallery pull request #9727
Opened 2023-11-06 06:17 UTC by ryuyu

Should address an odd issue with support requests where we get reasons that we shouldn't be seeing in support DB.

2023-11-06 16:52 UTC, erdembayar commented on src/NuGetGallery/Controllers/PackagesController.cs
> +        private static readonly IReadOnlyList<ReportPackageReason> DisallowedReportAbuseReasons = new[]
If it's enum then do we need to enumerate manually here? If we change the original enum then have to make make change here too.
You can create enum extension that enumerate any enum and list the values.

2023-11-06 16:54 UTC, erdembayar commented on src/NuGetGallery/Controllers/PackagesController.cs
>              if (package == null)
Should we delete do one considering it's duplicate of line #1484-1489.

2023-11-06 21:19 UTC, ryuyu commented on src/NuGetGallery/Controllers/PackagesController.cs
> +        private static readonly IReadOnlyList<ReportPackageReason> DisallowedReportAbuseReasons = new[]
I think the idea with this overall was clarity for reading the reasons. If there is a better way to do this while maintaining the clarity, I'm open to suggestions. It felt a little weird to me as well to have this many repeated lists. I believe @drewgillies brought up a similar concern.

2023-11-06 21:20 UTC, ryuyu commented on src/NuGetGallery/Controllers/PackagesController.cs
>              if (package == null)
You are absolutely right. Looks like I left the null package check both before and after the reasons check. I'll clean up the one down here. Good catch!

2023-11-08 05:53 UTC, drewgillies requested changes

2023-11-08 05:53 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +        private static readonly IReadOnlyList<ReportPackageReason> DisallowedReportAbuseReasons = new[]
I'd be inclined to call these SafetyReportAbuseReasons rather than Disallowed... as they are only Disallowed sometimes.

And rather tha double-up on these lists, you could:
- remove all entries from the ReportAbuseWithSafetyReasons collection, i.e. the whole initialization statement
- add a statement to the constructor which populates it with the union set of this list and ReportAbuseReasons.
That way, if a new reason comes along (and this space is always in flux, so who knows...) it just needs to be added in one place.

2023-11-15 21:25 UTC, erdembayar approved these changes

2023-11-15 21:29 UTC, erdembayar commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            var ReasonChoices = _featureFlagService.IsShowReportAbuseSafetyChangesEnabled()
Don't we use camelCasing for var names? Usually PascalCase name is usually used for constants and static vars at top.

2023-11-15 22:28 UTC, shishirx34 approved these changes

2023-11-16 13:32 UTC, joelverhagen commented
@shishirx34! 
![image](https://github.com/NuGet/NuGetGallery/assets/94054/f24017d7-21f7-4748-9325-5c714da52718)
Hey man 👋!!!

2023-11-16 23:41 UTC, ryuyu commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            var ReasonChoices = _featureFlagService.IsShowReportAbuseSafetyChangesEnabled()
I copied the casing used in the other method. I THINK this is sent back to the frontend, so it was named like this to make it distinct from serverside variables, but I am unsure.

2023-11-16 23:42 UTC, ryuyu commented on src/NuGetGallery/Controllers/PackagesController.cs
> +                    && (_featureFlagService.IsAllowAadContentSafetyReportsEnabled() || PackageHasNoAadOwners(package))
I suspect this MAY not be necessary anymore? It seems that if a reason is in the SafteyReportAbuseReasons, we just reject it since ReportAbuseReasons no longer contains the Safety reason? @drewgillies is that correct?

2023-11-17 00:54 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +                    && (_featureFlagService.IsAllowAadContentSafetyReportsEnabled() || PackageHasNoAadOwners(package))
It's still necessary because in a scenario where we don't want to allow safety reports on enterprise packages (i.e. a package with >=1 AAD account owners), this will cause the list to revert to not having safety categories.

2023-11-17 05:15 UTC, ryuyu commented on src/NuGetGallery/Controllers/PackagesController.cs
> +                    && (_featureFlagService.IsAllowAadContentSafetyReportsEnabled() || PackageHasNoAadOwners(package))
The display of the list is done on a different method right?
For the POST, if we see a safety reason, we reject, regardless of the state otherwise if I'm understanding this correctly, right?

IE state of abuse submission with safety reason
Regular package: Disallowed safety reasons, Reject.
AAD owner package: Safety reason disallowed. Reject.

So it seems when processing a POSTed request in gallery, we will always reject a Safety reason, regardless of if owners are AAD or not.

2023-11-30 07:49 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +                    && (_featureFlagService.IsAllowAadContentSafetyReportsEnabled() || PackageHasNoAadOwners(package))
We discussed this offline, and the missing piece was the always-blocked categories (copyright, NCDII). @ryuyu will reiterate and we'll continue the review.

2023-12-15 05:36 UTC, drewgillies approved these changes

2023-12-15 05:37 UTC, drewgillies commented on src/NuGetGallery/Controllers/PackagesController.cs
> +            ReportPackageReason.ViolatesALicenseIOwn,
ViolatesALicenseIOwn is about to become denied as well, but that can be a separate change.

2023-12-15 11:33 UTC, RiadGahlouz approved these changes

2023-12-15 20:13 UTC, merged