[UI] Add new themes to Packages List view page
NuGet/NuGetGallery pull request #9852
Opened 2024-03-13 22:54 UTC by martinrrm

Addresses https://github.com/NuGet/NuGetGallery/issues/9854
Figma: https://www.figma.com/file/ZaAD9rDujh8JDkRF4q9Fd8/NuGet---Simple-theme-updates?type=design&node-id=61%3A9109&mode=design&t=Urj8iIoXc4thBO3E-1
Spec: https://github.com/NuGet/Engineering/pull/5209
## Description

These PR add's colors/theme for the Package List view, for this page we added:
- transparent button
- new styles for checkbox and radio buttons
- new style for switch.
- new theme for badges.

#### Dark Theme
![image](https://github.com/NuGet/NuGetGallery/assets/43253759/9e37c137-f88c-40c6-a318-916425bb8b32) 

#### Light Theme
![image](https://github.com/NuGet/NuGetGallery/assets/43253759/b1712728-79fb-4882-bd4b-17744e4b5018)

### Transparent button
#### States

|  State | Dark |  Light |  
|---|---|---|
| Focused | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/a6c8db99-4552-43db-9130-eab66bcada10)  | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/acaa4eac-ae92-4690-ba04-fcff38d9e962)  | 
| Hover | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/2f5dfb63-105f-4eb0-a8c1-ad5414b5ea01)  | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/ca5eb696-f1d0-49a7-b722-1eff23c0f658)| 
|  Pressed | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/32cd793e-3b1e-47e3-af57-6f9758285b34)| ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/dcca4a34-7d74-4230-ba5f-7c5681cd3c25) | 
| Rest | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/ea3ad213-f235-4e2d-95e1-d051152a6acb) | ![image](https://github.com/NuGet/NuGetGallery/assets/43253759/fbec4f06-8e19-44c1-9108-5c4897e11db2)|

#### Checkbox, Switch and TreeView
The icon button uses the new transparent button so the styles are the same.

##### Dark
![checkbox-dark-theme](https://github.com/NuGet/NuGetGallery/assets/43253759/3db32eb6-95b7-4990-b8b7-fdd5c53e266d)

##### Light
![checkbox-light-theme](https://github.com/NuGet/NuGetGallery/assets/43253759/2496af8d-1d53-4666-8c58-262313d3ec36)

#### Radio button
![radiobutton-dark-theme](https://github.com/NuGet/NuGetGallery/assets/43253759/6bb6246b-1c58-4f7a-ab5f-f3beb43ee802)

#### Badges

![image](https://github.com/NuGet/NuGetGallery/assets/43253759/7cf8deb5-9651-4dec-b333-a6dd458a945e)
![image](https://github.com/NuGet/NuGetGallery/assets/43253759/63d1a3ff-d625-4eb9-b754-0bfb8e4389d8)

#### Accessibility errors
### Links color are not accessible enough
I'll contact designers again to ask for guidance here. There are two options, add an underline for these kinds of links or change the color of hyperlinks
![image](https://github.com/NuGet/NuGetGallery/assets/43253759/41327d7e-bf71-48af-894c-f835f07931c3)

2024-03-13 23:10 UTC, martinrrm commented on src/Bootstrap/less/forms.less
> +    appearance: none;
Radio buttons and checbox's cannot be modified since they are elements that the browser renders, so we need to change its appearance to none

Doing display: none will make it unfocusable

2024-03-13 23:12 UTC, martinrrm commented on src/NuGetGallery/Views/Shared/_SearchBar.cshtml
> -        <button class="btn btn-default btn-brand btn-search" type="submit"
`btn-default` adds styles that are not needed, removing it to reduce the overriding of css properties

2024-03-13 23:12 UTC, martinrrm commented on src/NuGetGallery/Views/Shared/ListPackages.cshtml
> +                                        <span>
Added spans so we can select the text from CSS, otherwise is rendered just as text

2024-03-14 01:30 UTC, erdembayar commented
Please add link to main tracking issue and if there's any spec.

2024-03-14 21:12 UTC, martinrrm commented on src/NuGetGallery/Controllers/PackagesController.cs
> +                includePackageRegistration: true,
need to remove this too, bad rebase

2024-03-19 22:16 UTC, joelverhagen commented on src/Bootstrap/dist/css/bootstrap-theme.css
> +  color: var(--neutralForeground1Rest);
Since we are using less, what's the benefit of using `var(...)`? Can't we leave the explicit color and get  a bit more legacy support that way?

2024-03-19 22:36 UTC, joelverhagen requested changes
Do we use `var` in our CSS at all? I see it's supported on most recent browser versions but it seems strange to use this feature along with LESS transpiler, i.e. we are already "compiling" our CSS so why not sub the variables for real values for a bit of back compat. I don't feel super strongly but I'd like to at least understand the motivation of using this CSS feature for I believe the first time.

Do you plan on merging the PR as-is with the a11y errors or are you blocking on that?

2024-03-20 00:27 UTC, drewgillies approved these changes
This looks good to me, pending @joelverhagen's clarifications.

2024-03-20 00:27 UTC, drewgillies commented on src/Bootstrap/less/forms.less
> +    appearance: none;
This can be corrected for a11y with a span/div, right?

2024-03-20 19:37 UTC, joelverhagen approved these changes

2024-03-21 16:32 UTC, martinrrm commented on src/Bootstrap/dist/css/bootstrap-theme.css
> +  color: var(--neutralForeground1Rest);
Talked with Joel offline and we decided to continue with CSS variables, IE is the main concern since it doesn't support them, after merging into dev we will verify that the page is usable I'll track it here https://github.com/NuGet/NuGetGallery/issues/9875

2024-03-21 21:19 UTC, drewgillies commented on src/Bootstrap/less/forms.less
> +    appearance: none;
Discussed offline--my concerns were around tabbing to the control for a11y. This isn't affected by the change.

2024-03-21 21:29 UTC, merged