Fixing JS exceptions on profiles page
NuGet/NuGetGallery pull request #9904
Opened 2024-04-03 22:10 UTC by advay26

We're seeing some javascript exceptions for the profiles page. We use the same scripts file on the search page and the profiles page, and need to deal with null values properly to avoid exceptions. This should be fixed now.

2024-04-04 00:52 UTC, erdembayar approved these changes

2024-04-04 13:35 UTC, joelverhagen commented on src/NuGetGallery/Scripts/gallery/page-list-packages.js
>              filtersContent.style.display = (computedStyle.display === 'none') ? 'block' : 'none';
Wouldn't this need to go in the new `if` also since it uses `computedStyle`?

2024-04-04 13:36 UTC, joelverhagen requested changes
I think a bit more moving of code is needed to the new `if` condition.

2024-04-04 22:53 UTC, advay26 commented on src/NuGetGallery/Scripts/gallery/page-list-packages.js
>              filtersContent.style.display = (computedStyle.display === 'none') ? 'block' : 'none';
Yup, you're right. I'll make the changes

2024-04-16 22:10 UTC, erdembayar submitted a review, later dismissed

2024-04-16 22:44 UTC, advay26 commented on src/NuGetGallery/Scripts/gallery/page-list-packages.js
>              filtersContent.style.display = (computedStyle.display === 'none') ? 'block' : 'none';
I've updated this now

2024-04-29 18:15 UTC, joelverhagen approved these changes

2024-04-29 18:17 UTC, merged