migrate VerifyMicrosoftPackage.Facts.csproj to sdk csproj
NuGet/NuGetGallery pull request #9989
Opened 2024-06-05 03:34 UTC by SimonCropp

2024-06-05 18:24 UTC, joelverhagen commented on tests/VerifyMicrosoftPackage.Facts/VerifyMicrosoftPackage.Facts.csproj
> -    <RootNamespace>NuGet.VerifyMicrosoftPackage.Facts</RootNamespace>
The assembly name is changing, which is breaking out test script, I think.

2024-06-25 20:31 UTC, erdembayar commented on tests/VerifyMicrosoftPackage.Facts/VerifyMicrosoftPackage.Facts.csproj
> +    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" PrivateAssets="all" />
<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>

2024-07-09 17:53 UTC, erdembayar approved these changes

2024-07-09 18:31 UTC, erdembayar commented on tests/VerifyMicrosoftPackage.Facts/VerifyMicrosoftPackage.Facts.csproj
> -    <RootNamespace>NuGet.VerifyMicrosoftPackage.Facts</RootNamespace>
It's breaking our CI build.
file not found: xxx\tests\VerifyMicrosoftPackage.Facts\bin\Release\VerifyMicrosoftPackage.Facts.dll

2024-07-09 18:32 UTC, erdembayar requested changes
Please check my comment for break CI build

2024-07-10 01:25 UTC, closed without merging